### ISSUE TITLE
Disk state validation to avoid crashing on corruption

### ISSUE THREAD

**Issue by mbsanchez** [nzbget/nzbget#121]
I have fixed a crash on nzbget caused by a bad disk state: when an user has a bad disk state (caused by a system crash perhaps), the user can't start nzbget because it crashes on startup, I have debugged nzbget and I have found that the article size on diskstate file is different to the articles length on pFileInfo vector, to fix this and allow nzbget to run without crashing, I have made the next changes:

```
 daemon/queue/DiskState.cpp | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/daemon/queue/DiskState.cpp b/daemon/queue/DiskState.cpp
index e603e2c..e7229a4 100644
--- a/daemon/queue/DiskState.cpp
+++ b/daemon/queue/DiskState.cpp
@@ -1429,7 +1429,8 @@ bool DiskState::LoadFileState(FileInfo* pFileInfo, Servers* pServers, bool bComp
    iCompletedArticles = 0; //clang requires initialization in a separate line (due to goto statements)

    int size;
-   if (fscanf(infile, "%i\n", &size) != 1) goto error;
+   if (fscanf(infile, "%i\n", &size) != 1 || (size_t)size > pFileInfo->GetArticles()->size()) goto error;
    for (int i = 0; i < size; i++)
    {
        if (!bHasArticles)

```

I have a backup of queue folder that you can use to reproduce this issue, but i don't know how to attach the rar file.

**Comment by hugbug** [comment]
Yes, that's a problem. A corrupted disk state file(s) can cause all kinds of troubles since there is no any validation. What you have fixed is one place of probably hundreds.

May be a better more complete solution would be to store a checksum of file content and validate it before building objects from the file. Performance is always a concern so the solution must take this into account.

I'm changing the title a little and converting to "feature" for a next release.

**Comment by hugbug** [comment]
> have found that the article size on diskstate file is different to the articles length on pFileInfo vector

I had [another similar case](http://forum.nzbget.net/viewtopic.php?f=3&t=2504). After an investigation it turned out the problem wasn't the corrupted disk state file. Sometimes (it's not clear when) it may happen that after a deleting of file from queue its disk state progress file (which holds progress data for partially downloaded files) remain on disk. After a program restart the same file ID may be reused. This can lead to a situation when a disk state info file and a disk state progress file (for the same file ID) both exist but do not belong together. They are processed together nonetheless, causing the trouble.

This has to be fixed.

**Comment by hugbug** [comment]
> May be a better more complete solution would be to store a checksum of file content and validate it before building objects from the file. Performance is always a concern so the solution must take this into account.

I've developed checksum calculating (when writing) and validation (when reading). Since it's currently doesn't look like there is an issue with corrupted files I'm not committing the checksum solution yet, to avoid unnecessary performance overhead.
