### ISSUE TITLE
make install is failing on linux

### ISSUE THREAD

**Issue by rcdailey** [nzbget/nzbget#135]
Logs below:

```
user@server:~/nzbget-code$ sudo make install
make[1]: Entering directory '/home/robert/nzbget-code'
 /bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c nzbget '/usr/local/bin'
 /bin/mkdir -p '/usr/local/share/doc/nzbget'
 /usr/bin/install -c -m 644 lib/par2/AUTHORS lib/par2/README README ChangeLog COPYING '/usr/local/share/doc/nzbget'
/usr/bin/install: will not overwrite just-created ‘/usr/local/share/doc/nzbget/README’ with ‘README’
Makefile:2328: recipe for target 'install-dist_docDATA' failed
make[1]: *** [install-dist_docDATA] Error 1
make[1]: Leaving directory '/home/robert/nzbget-code'
Makefile:2632: recipe for target 'install-am' failed
make: *** [install-am] Error 2
```

**Comment by rcdailey** [comment]
Closing this issue since this error was a result of improper configuration.

**Comment by hugbug** [comment]
Is it working now? I haven't tested `make install` for a long time and not sure if it still works.

**Comment by rcdailey** [comment]
It's working just fine, I made the mistake of manually running autoconf / etc and it modified some scripts, which apparently caused some issues. Why don't you run `make install`? At least as an end-user, I need to do this so it gets installed properly on my system.

**Comment by hugbug** [comment]
> Why don't you run make install?

Because I run it from where it was compiled (during development) and on my download box I install via [universal Linux installer](https://github.com/nzbget/nzbget/wiki/Installation-on-Linux) (the box doesn't have a compiler to start with).

I consider the manual compilation of NZBGet as a thing for hard core users ;-) Most users should take advantage of universal Linux installer, which saves compiling hassle and gives easy updates via web-interface.

**Comment by rcdailey** [comment]
I was doing it manually because I thought that was the only way. Do I need to re-install a binary package simply to have auto updates setup? If NZBget is smart enough to build from latest in Git then I'd like to set it up that way. What do I need to do to get it working in the situation where I've been doing `make install` manually?

**Comment by hugbug** [comment]
The universal installer contains prebuilt binaries for many supported CPUs and works on most Linux systems including desktops, NAS, wlan-routers, media players, etc.

When a new stable or testing release is available an update can be installed via click in web-interface. The new binaries are fetched from download page and installed. Nothing is compiled.

The latest development version cannot be installed that way because I do not provide nightly builds.

There is no v17-testing release yet, for example.

See https://github.com/nzbget/nzbget/wiki/Installation-on-Linux for details.

**Comment by rcdailey** [comment]
I gotcha. In that case I will continue doing it by hand. It's not really that much trouble, also gives me a chance to make sure everything is working for you.

Thanks again for your help.

**Comment by hugbug** [comment]
Yep, another pair of eyes is good. Thanks.

**Comment by sbraz** [comment]
@hugbug can you please re-open this issue?
It may or may not cause the installation to fail depending on whether `configure` is run directly or regenerated with `autoreconf` but there is a problem indeed:
nzbget's `README` tries to overwrite libpar2's (and sometimes succeeds, hence the lack of error).

It's quite easy to reproduce: `./configure --prefix=/tmp/nzbget-17.0-testing/test/ && make -j9 && make install`

```
 /usr/bin/install -c -m 644 'lib/par2/README' '/tmp/nzbget-17.0-testing/test//share/doc/nzbget/README'
 /usr/bin/install -c -m 644 'README' '/tmp/nzbget-17.0-testing/test//share/doc/nzbget/README'
```

**Comment by hugbug** [comment]
Should be OK now.
