### ISSUE TITLE
Pre download nfo and scrape

### ISSUE THREAD

**Issue by nomandera** [nzbget/nzbget#139]
In theory if any queued nfo's were downloaded in advance independent of queue state/order it would open the door to a few new features such as showing raw nfo and pre parsing the nfo for URIs.

The benefits of this are obvious and multifold especially for users that maintain large paused queues but the arguments are similar to why nzb trackers do it.

**Comment by hugbug** [comment]
I don't like this for multiple reasons.
1. This is what indexers are for. You choose nzbs on indexers and their provide you with nfo. I don't see a use case in nzbget. Why queue nzb-files only to inspect nfos if you can do that upfront on indexers?
2. One possible scenario would be to queue multiple versions of the same title, inspect their nfos, then decide which one to download. But that would not work because all secondary nzbs go straight to history as duplicates.
3. A technical possibility to set priorities for each file within nzb independently and therefor to download certain files such as nfos with higher priority existed in nzbget in older versions and was eliminated in v13. No one has ever used this feature and no one has missed it when it was removed.

**Comment by nomandera** [comment]
I dont think I can make a case for this being useful to everyone but I can make a case where it would be useful to me and we can accept/drop from there.

Two scenarios:

Not all trackers let you see the nfo and not all filenames tell you all the info you need e.g. alternate languages, source etc so you end up googling randomly or manually partially grabbing the nfo to examine for further details.

A backlog of paused items in queue. Items were added based on a "for future download" assessment so later it becomes an manual exercise to locate the content link or read the nfo (once you locate which tracker it came from since that may be lost on nzb import)

Also the nfo (and associated extracted URIs) are typically a tiny goldmine of information that may be useful to keep along side the history.

**Comment by hugbug** [comment]
Assuming we can download nfos, what's then? Is this all you need or do you expect this nfos being displayable in nzbget web-interface? I really don't want to go that far and making some kind of file or media manager from nzbget.

**Comment by nomandera** [comment]
Can I have a think about this and perhaps give others a chance to comment. A feature that is useful only to me is not something I would want to request.

**Comment by hugbug** [comment]
Sure, I'll think about it too.

**Comment by vergessen** [comment]
I personally think this is feature bloat.   A end user can already create nzbs to download nfo's if they so desire.  I am worried about having to display/show/delete/manipulate these files after the fact.   I think it is cleaner if nzbget stays out of the way, lets the user download them(hold the rest of the files on pause).  The end user can then review with their systems tools and remove as needed.

**Comment by hugbug** [comment]
Closing this as out of scope.
