### ISSUE TITLE
Minor UI enhancements - Sorting

### ISSUE THREAD

**Issue by brosoft-dev** [nzbget/nzbget#166]
_(Just an idea - to be approved as a real FR by OP)_

Currently, new downloads are appended to the current list - regardless.

**Suggestion: A more structured/hierarchical download list**

Proposal:
- The default download view is auto-sorted by a mixture of status and priority:
  - First criteria [Group by status: {Active/Downloading, Post-download related, Errored, Paused}]
  - Second criteria (applies within each group above) [Order by priority]
- Downloads that are added manually or via API insert in the appropriate position.
- Downloads are processed in this order (ie. so going from global state Paused to Resume, the first item in the list would begin downloading, it would finish and move down to where PP-related statuses exist in the list while the new topmost item would begin downloading)
- Editing a download's priority re-sorts its index in the list on save

That way, paused download items are always at the bottom of the list. New items are always included in the top group, and API clients that utilize priority when adding items will be better reflected visually in the download queue list.

**Additional**

Make the "Select All" checkbox a tri-state (Unselected, Current Page, All Pages)

**Comment by hugbug** [comment]
Thank you for your suggestion. Sorry for not having written back sooner.

The automatic queue sorting was [discussed on forum](http://forum.nzbget.net/viewtopic.php?f=10&t=1253) but we couldn't agree on how it should work.

I can understand how sorting on priority can be useful - to easier find active item if queue is large and since former SAB users are accustomed to it.

Sorting by status however doesn't convince me. Any change of activity will reorder items and will probably make it harder to use the program?

**Comment by biltongza** [comment]
I have my downloads set up so new items are set to very high priority, so I want to be able to view those first, but they always get lost in the hundred plus downloads queued.

I am sure I'm not the only one with this sort of use case and quite honestly it baffles me that this isn't built in already. When I googled it I find this forum post from 2011 saying you added it: http://forum.nzbget.net/viewtopic.php?f=3&t=353 but that clearly isn't there anymore. Granted I have no idea what's happened since 2011 since I only started using NZBGet this year :)

I also sometimes just want to see what is downloading, but I have to manually sift through everything to find what is downloading. I'm all for sorting by status.

Update: so I just started looking through some of the code, and did some experimenting in F12 and found that if I throw `Downloads.sort('priority')` in the console it works perfectly so surely it's trivial to make a button for this? I'm not familiar with JS but I will try my hand.

**Comment by hugbug** [comment]
The forum post you linked to talks about **priorities**. They were added and are of course still there.

> it baffles me that this isn't built in already.

What exactly? It seems everyone means something different when talking about sorting.

**Comment by biltongza** [comment]
Ah, then I misread that thread, apologies. 

I should have been more clear, I meant sorting on priorities.

**Comment by hugbug** [comment]
Do you mean automatic sorting on priorities (after every change of queue)?

As for manual soring there is alreary manual sorting on name, category, size and remaining size - via click on column header (it even works on selected items). Manual sorting on priority isn't available in webui because there is no column for priority. I don't know how to add this function nicely to UI.

**Comment by biltongza** [comment]
That's what I meant, manual sorting on priority. I don't think there's anything really wrong with adding another column to the queue, there's one for category why can't there be one for priority?

That said, manual sorting on status would be nice too.

**Comment by hugbug** [comment]
Closing issue. The priority column will be handled in a separate issue.
