### ISSUE TITLE
CMake Build System

### ISSUE THREAD

**Issue by rcdailey** [nzbget/nzbget#179]
I am working on adding CMake build scripts to the nzbget project. I'm not well-versed in makefile and configure scripts. Could you kindly give me an overview of the install paths for nzbget? What should the structure look like? Basically all the paths used in `make install`. Ideally windows uses the same structure but under `C:\Program Files`.

I can setup CMake to do this. I already have it building the executable.

**Comment by hugbug** [comment]
Just do:
`make DESTDIR=anydir install`
Then you'll have everything installed into _anydir_ as if it were root directory.

This will give you the classic structure for Posix, where files are spread across the file system. I don't use this structure in Linux installer, which installs all files into one location; that makes the system clean and simplifies deinstallation.

On OS X the program is bundled as application (one directory contains everything).

Using classic Posix directory structure on Windows doesn't make sense either.

I know you are doing this with best intentions but please understand that adding the cmake scripts into nzbget project requires supporting of this alternative build system in the future, the time I'd rather spent doing other things.

**Comment by rcdailey** [comment]
Bear in mind the support will only be the same or less than what you are
doing today. You have to maintain multiple build systems right now. This
will consolidate down to one. Also I wouldn't really be so concerned about
upkeep. Unlike make scripts, cmake is simple. If your time is spent adding
filenames to a list every time you add source files then that's reasonable
I think.

My inquiry was more in regards to specifically what files in your
repository get installed. I guess I'll keep digging into the makefiles to
figure it out.

**Comment by hugbug** [comment]
> My inquiry was more in regards to specifically what files in your
> repository get installed.

And that was the answer:

> Just do:
> `make DESTDIR=anydir install`
> Then you'll have everything installed into _anydir_ as if it were root directory.

Or haven't I understood the question correctly?

> You have to maintain multiple build systems right now. This will consolidate down to one. 

Only if CMake could replace autotools but can it? Does it support cross-compiling and if it does how good is it working? Cross-compiling is one of the main thing I need from the build system. With autotools it works everywhere I tried it.

I also don't see why use CMake on Windows if I need to support project file for Visual Studio anyway (in order to develop in VS).

**Comment by rcdailey** [comment]
Sorry for not being clear.

What I mean is, when you do `make DESTDIR=anydir install`, what files get copied? What directories do the files get copied to, and if the directories are different depending on file type, where are those defined/mapped?

This is mostly due to my ignorance of linux development. I am still learning how it all works, I mostly develop on Windows.

I recommend you read up on CMake a little bit, because it'll explain its purpose better than I can:
https://cmake.org/

I refer to CMake as a meta-build system. It doesn't actually build anything itself. However, it generates makefiles and projects for other toolchains. For example, on Windows you tell it to generate Visual Studio project files. You open those, and you can build normally using Visual Studio. You don't make project changes directly to the VS project files. Instead, you update the CMake scripts, re-generate the VS projects again, reload the solution, and continue on. It isn't as tedious as it sounds, though. When you want to add files to your project, you update the `CMakeLists.txt` files (these are similar to `Makefile` files for make) with the new files. You don't add them directly to the Visual Studio project files. Whatever project files CMake generates are _temporary_ and disposable. They are not checked into version control. Only the CMake scripts are versioned and _they_ determine changes to the projects.

Using those same exact CMake scripts, on a different platform you can generate ninja scripts, makefile scripts, eclipse projects, and scripts/projects for many other tools. This functionality is really important when you're cross platform because you are maintaining 1 authoritative set of scripts for your build system instead of 1 per unique platform or toolset.

There are a few reasons I'm doing this for the nzbget project:
1. I love nzbget and as a developer I want to help out.
2. I have used CMake for over 7 years and I am very comfortable and knowledgeable with how it works. I see the value it can add to your project and hopefully I can help you understand that value and appreciate it.
3. Personally I feel that maintaining CMake is much easier. Arguably most important of all is how naturally CMake scripts read. it looks closer to Python, where it "reads like a book". IMHO, autotools, configure scripts, makefile scripts remind me a lot of Perl. It's loaded in detailed syntax, with unintuitive flow and structure. There is a lot more boilerplate in those systems. I don't expect you to agree here, this is just my personal opinion.
4. I'm confident CMake will simplify your build pipeline and exceed your expectations and requirements. I've yet to find a case where CMake does not end up being a superior choice.

Happy to go over any detailed questions you have. After all, this isn't a marketing campaign. It has to work in practice, otherwise there is no point. And a big part of that is understanding your requirements beyond what I've tried to learn just by reading your scripts.

Concerning your question about `autotools`, I honestly don't have any experience with it. I did some googling and I found [some opinions on autotools vs cmake](http://stackoverflow.com/a/18291580/157971), so I think there is a consensus in the community that CMake might be better, but again depends on requirements.

I am cross compiling with CMake right now using a custom toolchain file for Android NDK (ARM GCC toolset). This is not intuitive to setup, however. Normally CMake will compile for the platform you're running on. It keeps things simple for you by finding toolchains automatically for you based on the assumption that you are _not_ cross compiling. If you are, it can't make these assumptions and you will, at the very least, need to point it to the right compilers, linkers, and system libraries. For example, CMake respects the `C` and `CXX` environment variables if you have them set. It will use those toolchains if you specify them.

Maybe if you have the time you can go over how you are cross compiling and I will make sure that what I am doing factors that in. Once you setup cross compilation toolchain file, you can check that in and reuse it in the future. So it's a 1 time setup.

Definitely let's get a dialog going for this. It'll be good to make sure all requirements are covered, and also help answer any questions/concerns you have.

**Comment by hugbug** [comment]
> `make DESTDIR=anydir install`

You need a Linux machine (VM). Once you have setup compiling tools and can compile nzbget, you use the command `make DESTDIR=anydir install` and nzbget will be installed into directory _anydir_ by maintaining the whole directory structure inside anydir. Now you can easily see which files where were installed. That's an alternative to read Makefile.am (but don't try understanding Makefile.in or Makefile (without extension), they are generated).

I'm not a big liker of autotools but they do their job and switching to another tool sounds like a pain. Since the current build system isn't broken I'm not motivated to do a switch, at least not by myself.

If you want nzbget to use CMake you are the one implementing this for all platforms and I'm the one answering your questions related to nzbget. Not the other way around :smile: 

I have a bunch of things to work on (see issue tracker) and switching the build system isn't one I'd like to work on actually.

### So if you are willing to try CMake with nzbget on Linux:
- find a Linux VM to work with, install compiling tools;
- build nzbget as documented in [Installation on POSIX](https://github.com/nzbget/nzbget/wiki/Installation-on-POSIX);
- create distribution archive with `make dist` (one of the autotools feature);
- make CMake working;
- implement configuration switches like the existing **--disable-curses** or **--with-libgnutls-includes=/path/to/gnutls/includes**, etc.;
- now tricky configure detections ([configure.ac](https://github.com/nzbget/nzbget/blob/develop/configure.ac)) such as (a few examples):
  -  is function "ctime_r" taking two of three parameters?
  - does system have function "getaddrinfo"? if it doesn't - does it have "gethostbyname_r" and if it does which version of this function is available - the one taking three, five or six arguments?
  - is "backtrace" library call available?

Once you have CMake working on one platform do work further and test the build process on few other systems (VMs) such as various Linux distributions, FreeBSD and OS X.

> Maybe if you have the time you can go over how you are cross compiling and I will make sure that what I am doing factors that in. 

To build Linux installer (which includes cross compiled binaries for six platforms) I use toolchain [Buildroot](http://buildroot.uclibc.org). I've documented the build process [here](https://github.com/nzbget/nzbget/blob/develop/linux/build-info.txt).

### A positive thing:

nzbget v17 requires compiler supporting C++14 on the build machine. This requirement alone should hold back many ancient systems. There is a good chance that a system having C++14 compiler also has CMake. And it will not be a new fatal dependency.

**Comment by rcdailey** [comment]
Thanks for the tips, I will make sure everything is addressed. I appreciate your feedback.

Also it seems as if you are misunderstanding. I get that you are busy and have no time to spend on CMake related things. This is why I am doing it. I would not expect you to do anything other than share your opinion on how you want it to work. I do value your feedback, so I may ask you questions about how you want things to work, especially if there isn't a straightforward 1-to-1 mapping between CMake and your current tooling.

I will keep you updated on my progress. Thanks and I look forward to demoing this to you in the future.

**Comment by hugbug** [comment]
> Also it seems as if you are misunderstanding. I get that you are busy and have no time to spend on CMake related things. This is why I am doing it.

I thought you don't want to do Linux stuff. It's good that I was mistaken about this. I'll happily answer questions or provide other feedback you need. Thank you for participation.

If you don't have other questions at this moment I suggest we close the issue and when you have something to discuss you can reopen it any time (or contact me via email if you prefer).

BTW, just saw a [survey](https://blogs.msdn.microsoft.com/vcblog/2016/02/29/developing-c-cross-platform-projects-with-cmake/) in MS blog about CMake. Looks like they are concerned about better integration with VS.

**Comment by rcdailey** [comment]
Yes, I did take that survey. This is just my suspicion, but it feels like they will probably build CMake integration into Visual Studio at some point. They already have contributed to the CMake project to support their new android development features in VS2015. That would be amazing.

I only meant to state that I have limited experience and knowledge of Linux development. However, I am very much still interested in it and wish to do it. It's a great way to learn and get familiar with it.

I am fine closing this ticket for now. I will refer to this issue number in my commit messages. Thanks for all your feedback.
