### ISSUE TITLE
Separate WatchDir & NZBdir

### ISSUE THREAD

**Issue by rodalpho** [nzbget/nzbget#186]
Under SABnzbd I locate my watchdir on dropbox, so I can easily queue up downloads from outside my network. I have little subdirectories to classify the download for "Movies", "TV", "Music", and "Books".

NZBget combines the watchdir with its NZBdir. If I put the NZBdir on my dropbox, it would constantly be sending NZB files to every computer I have on that dropbox, which includes two desktops at work-- clearly not a desirable situation! 

Also, I would be annoyed by dropbox new file added/deleted notifications cluttering my screen every time Sonarr adds/finishes a new download. Pretty annoying.

My request is simple, to separate the WatchDir and NZBdir so NZBget behaves the same as SABnzbd. This is the sole reason why I'm still using SABnzbd as NZBget is clearly superior in every other respect.

Thanks for your consideration!

**Comment by hugbug** [comment]
Not sure how this should work with scan scripts. Need to make more thoughts about this.

**Comment by rodalpho** [comment]
Many ways to address that, most of which would require scan scripts to be aware of a second directory. But one very simple process flow would be:

1) File added to WatchDir?
2) Move it to NZBdir...
3) Then treat it like normal!

**Comment by hugbug** [comment]
Yes, that would be the easiest. On the other side when having two directories we can improve the handling to avoid renaming of nzb-files to nzb.queued.

**Comment by rodalpho** [comment]
Yep, I just outlined what it would take for my _personal_ needs to be satisfied. Thanks again for your consideration!

**Comment by hugbug** [comment]
> for my personal needs

What about writing a simple script which starts on system boot and periodically moves all files from Sync-Folder to NzbDir? Something like:

``` shell
#!/bin/bash
while true
do
    mv /syncdir/* /nzbget/nzbdir
    sleep 5
done
```

The move-command will be probably more complex to handle subdirectories, google for "bash move subdirectories".

**Comment by rodalpho** [comment]
That... would do it, yes. Could just pop a simple command in cron. Not particularly elegant, but it would do the trick. Something like

`*/5 * * * * /usr/bin/find /home/nzb/Dropbox/NZBs -type f -iname '*.nzb' -exec mv {} /home/nzb/.nzbget/nzbdir \; >/dev/null 2>&1`

If you decide not to make the change inside NZBget, that's what I'll do.

**Comment by rodalpho** [comment]
What discussion are you inviting? I can't imagine anyone is actually _against_ this option. Only question is if you guys feel it's worth the effort to add. I do personally still want it and am watching this issue, if that means anything.

**Comment by hugbug** [comment]
I was hoping that script authors write their feedback as the new behavior will affects how scan scripts work.

**Comment by rodalpho** [comment]
No response must mean they're cool with it, right? (heh)

**Comment by Magoo204** [comment]
Definitely would love to this added, Makes total sense!

**Comment by rEes9P** [comment]
Would love to see this added too

**Comment by caronc** [comment]
It might be easier to just use the script approach TBH. Heck, you could easily build a (NZBGet) scan script that does the moving of these nzb-files for you. The script would just take directory paths as it's arguments (in your case, one of them being a Dropbox directory). Then schedule it to wake up periodically with NZBGet (not a cron) to do the bidding. 

**Edit**: See this new script I created for you called [nzbget-dirwatch](https://github.com/caronc/nzbget-dirwatch)

**Comment by rodalpho** [comment]
The script is easy enough to write; I already did it myself and scheduled in cron rather than inside nzbget. Two issues.

1) It _isn't_ easier. It's yet one more thing to maintain in my configuration.
2) It's an additional disk access every X minutes, stopping it from sleeping. 

Adding a simple separate watchdir inside nzbget would be a _far_ superior solution.

**Comment by caronc** [comment]
@rodalpho see the link I provided, it's an actual NZB-Script maintained through NZBGet itself (same central configuration). No cron is necessary (so no separate configuration at all).  The script can additionally detect Zip files containing NZB-Files too and moves them for processing.  It has a variable configuration setting and [thanks to HugBug it will be even easier to use in NZBGet v18](https://github.com/nzbget/nzbget/issues/304#issuecomment-260747952)

So in lieu of your concern:
1.  It's an NZB-Get script so it uses the same central configuration as NZBGet and accessible through the same configuration GUI (as already stated above).
2.  Whether NZBGet polls multiple directories itself, or a plugin associated with it does instead has absolutely no bearing at all. You're still polling the directories on a configurable clock one way or another.

> Adding a simple separate watchdir inside nzbget would be a far superior solution.

That opinion is purely subjective; NZBGet is superior at so many levels and the fact that most needs (especially the obscure ones) can be solved through a plugin that connects directly to it.  This alone makes NZBGet incredibly versitile which is especially useful (and meant) for situations like yours. Seriously, check out the plugin I wrote (literally for you because I felt like helping); you may find it useful!

**Comment by hugbug** [comment]
Closing this topic since @caronc has provided a solution for sync with dropbox or other services whereas changing the behaviour in NZBGet is difficult without breaking of existing scan scripts.
