### ISSUE TITLE
Servers on Level 1 never get used

### ISSUE THREAD

**Issue by Spence1115** [nzbget/nzbget#187]
Hi

I've got a server on Level 0, and another on Level 1. The Level 0 one went down recently, but NZBGet never fell back to the Level 1 server. I even disabled the Level 0 one, and everything just went into 'queued'. When I set the Level 1 to 0, it worked, and I could connect fine, but it just wouldn't do anything on Level 1

**Comment by hugbug** [comment]
1. NZBGet expects all news server to be functional. If a connection cannot be established NZBGet waits until the server becomes available and doesn't go to higher levels servers. This may be improved in #155.
2. When all servers of level 0 is disabled the download is practically paused. This is to avoid accidental using of (costly block) higher level servers.

In other words all you describe is a correct behavior whereas the first part may be improved in the future.

**Comment by hugbug** [comment]
Closing the issue as there is nothing to do here.
Feel free to reopen or write back if you need further assistance or if I missed something.

**Comment by ghost** [comment]
When no level 0 servers are enabled, there should be a warning about this. I was wondering why all downloads were sitting at "queued" even with force priority. I saw no mention of downloads being paused because of this in the log.

**Comment by frtrnwly** [comment]
First off I wanted to say thank you for the application and all of your efforts. It is a great app.

Recently, I have noticed similar behavior. I have 3 servers at level "1". All three servers were down because of inability to verify certificates (same hosting service - Newshosting - European servers) 

A fourth server (Newshosting  - US server) was at level "5" but the connection using the certificate was working. However, NZBGet never moved to the level "5" server and nothing was being downloaded. I tried setting the European servers (all 3) to Active="No" and NZBGet still never moved down to my level "5" server. It wasn't until I completely removed all of the level "1" server that NZBGet started downloading again.

None of my servers are set to "optional". Would be helpful if there was a way to check that all servers in a group that are not operational could be checked and NZBGet could move to the next non-optional group to check to see if they are operational. Or that a message could be presented to the user saying there are "no servers are currently operational".

**Comment by hugbug** [comment]
@frtrnwly what you describe is a correct behaviour.

>Would be helpful if there was a way to check that all servers in a group that are not operational could be checked and NZBGet could move to the next non-optional group to check to see if they are operational.

The definition of "optional" is that nzbget can move on if such servers are not connectable. If you do want exactly this then just define them as optional. The default (non-optional) behaviour is that nzbget expects the servers be reachable. In this regard a "download failure" (which causes increasing of level) is a proper "article not found" response from server. A broken connection isn't a "download failure" but rather a "connection failure" and nzbget will retry.

**Comment by frtrnwly** [comment]
Thanks for the prompt reply. 

Your explanation of "optional" servers is "optional non-reliable server." I wouldn't say that the US server was non-reliable, just that it is not one of my preferred servers. So that was a little confusing to me but I will make that server optional as you suggest.

Regarding setting all of my level "1" servers to Active="No": shouldn't that have forced NZBGet to move to the next available group of active servers and in my case my level "5" server?

**Comment by hugbug** [comment]
> Regarding setting all of my level "1" servers to Active="No": shouldn't that have forced NZBGet to move to the next available group of active servers and in my case my level "5" server?

There is a special check that prevents exactly this - if all servers of level 1 are disabled the download stops. That was made this way to prevent accidental downloading from higher-level (usually costly  block accounts) when all (usually unlimited) level-1 servers are disabled.

**Comment by frtrnwly** [comment]
Again, thanks for the prompt reply.

Disabling as it is done makes sense now. My only suggestion would be to indicate to the user that there are "no currently available servers for use based on current settings". Might save you some time in the future for having to answer questions like mine :-)
