### ISSUE TITLE
nzbget as a non caching NNTP proxy

### ISSUE THREAD

**Issue by nomandera** [nzbget/nzbget#202]
I have debated internally for months if this is to random a feature request to post for consideration and have finally concluded better to ask than not.

There are very few NNTP proxys in existence, even fewer that are actively maintained and none that have anywhere even close to the capabilities of nzbget when it comes to levels, groups and fill servers.

I have no clue as to what the backend scale to this request is but in my ideal world nzbget would be the read only non caching middle man to all Usenet servers for all users usenet requests.

Will type more if the idea is of interest.

**Comment by hugbug** [comment]
> for all users usenet requests.

Wait, are you trying to tell that you use Usenet for more than downloading stuff?

NNTP proxy means the program must act as an NNTP server. This is far more than what NZBGet can now, acting as a client only.

That could be a separate project. Sure some parts of NZBGet could be reused but probably not so many. This is not something I personally could work on since I don't have any extra time for that (considering all feature requests related to the core NZBGet functionality). I could provide help with understanding internal NZBGet structures if some one wants to reuse them though.

Sorry to disappoint you but thanks for asking anyway.  :thumbsup:

**Comment by nomandera** [comment]
No thats more than fine it was as an "out there" request as I could make.

Appreciated and closing :)
