### ISSUE TITLE
Separate History path from Queue path

### ISSUE THREAD

**Issue by Darkknight33** [nzbget/nzbget#216]
Recently, I noticed a performance degradation happening with nzbget (16.4) par check & repairs. Taking a closer look, I saw literally 15,000+ 1kb files, some months old sitting in the queue directory. I stopped NZBGet, cleared everything but the most recent queue files, about 11k, and restarted it. A day later, there were 10K files in there again. These tiny writes are hammering the crap out of my SSD, which only has the main dir + queue dir on there. God knows how long it's been eating up the write life of that. SMH. 

Anyway, all of my download, check, and repairs happen in a dedicated 28GB ram drive to avoid bottlenecks associated with using HDDs, or life issues with SSDs. Made sense then to move the queue dir onto the ram drive which won't care about the load. The downside of this is that the history, feed, and statistics are also tied up with the queue and are lost on reset. It seems like it would make a lot more sense to have the low impact writes such the history & rss feeds moved to their own paths. 

Admittedly, this probably wouldn't impact a lot of users, but from a design perspective I don't understand why the history would be in the queue directory and not the log directory anyway.

Also, having just upgraded to v17-testing, I notice comparatively no fragmentation in the ram drive. Fragmentation in a ram drive is irrelevant, but I did want to point out the difference is night and day between 16.4 & 17.0-testing-r1686. I was watching it a lot over the past couple days while I was defragging my scratch drives.

**Comment by hugbug** [comment]
> I noticed a performance degradation happening with nzbget (16.4) par check & repairs. 

When we talk about performance I'd like to see numbers. That's very unlikely that the files in queue-directory affect par-check. Why would they?

> I saw literally 15,000+ 1kb files, some months old sitting in the queue directory.

There were a bug, that not needed files were not always removed. In #121 a cleanup routine were added which removes unnecessary files on program start and prints a message about this. Now I will be keeping eye on it to catch any other bugs which result in orphaned files in queue-directory.

> God knows how long it's been eating up the write life of that.

The structure of disk state files is optimized to minimize amount of disk operations. These small files help increasing life of your SSD, actually, by avoiding unnecessary writings.

> from a design perspective I don't understand why the history would be in the queue directory and not the log directory anyway.

Poor option name perhaps. The directory keeps the programs state and should probably be called "StateDir". There is also no log-directory. History isn't just log, it can be edited in many ways.

> It seems like it would make a lot more sense to have the low impact writes such the history & rss feeds moved to their own paths.

In #207 the queue and history were separated into two files (named "queue" and "history"). The files are still in the same directory. Having separate directories for parts of program disk state doesn't feel like a good idea to me. All these files belong together and should be treated as one database. Storing them in different locations creates risks for mismatches.

> having just upgraded to v17-testing, I notice comparatively no fragmentation in the ram drive. 

If you on Windows it must be #195. Now we have an explanation for "performance degradation happening with nzbget (16.4) par check & repairs".

As a general tip about disk IO - check if you have option **ContinuePartial** enabled, which causes more often writes into the directory.

**Summary:** it seems everything is fixed in v17 already.

**Comment by Darkknight33** [comment]
Thanks for replying so quickly. I appreciate your explanation.

Continue Partial is disabled.

I suppose I wasn't very clear in that I didn't think the queue files were causing that specific performance issue, just that because of the performance issue I found the queue directory had thousands of files. Even after updating to v17, there are still 6,000+ files floating around in the queue directory. 

Let me just get more to the point. Since everything is happening entirely in RAM on my system, is there some combination of settings that will allow me to not generate the queue files to begin with? If that's the case, I can keep history on disk and not worry about queue file writes.

**Comment by hugbug** [comment]
There is option **SaveQueue** which can be used to disable saving of program state but it's not possible to disable queue independently from history. They are very tied. The tiny files are also used by history too.

If you are concerned about SSD wearing you can put the QueueDir on HDD. Although the directory contains many files they are written rarely and don't require extra fast storage.

You have not specified your OS and exact nzbget version. I assume you run nzbget 17.0-r1686 on Windows. In that case you don't have the latest development version with the mentioned fix for orphaned queue files yet. There is a chance the fix reduces the number of files greatly.

If you want to try the develop version send me a note to nzbget@gmail.com with info about OS and CPU (if not Windows).

**Comment by hugbug** [comment]
Closing this. Feel free to comment or reopen if you have further questions.
