### ISSUE TITLE
Include fake detection for media files

### ISSUE THREAD

**Issue by jwillmer** [nzbget/nzbget#219]
Currently there is a extension that does this job quite good:

> Detects nzbs with fake media files. If a fake is detected the download is marked as bad. NZBGet removes the download from queue and (if option "DeleteCleanupDisk" is active) the downloaded files are deleted from disk. If duplicate handling is active (option "DupeCheck") then another duplicate is chosen for download if available.

Could be nice to have it as a build in option?

Github Link: [FakeDetector](https://github.com/nzbget/FakeDetector)

**Comment by hugbug** [comment]
I understand that from user's point of view it's better to have **everything** integrated. The purpose of extensions architecture is to make it easier for other users to contribute and share their extensions. 

Another point is that making certain things in scripted language is much easier than implementing the same functionality in C++, especially when the work can use existing libraries (python is reach of them).

The third point is that the fake detection script already exists and does its job.

Since my free time is limited I have to choose wisely features to work on. I hope you can see that reimplementing something that already exists and works well isn't that wise in my opinion.

**Comment by jwillmer** [comment]
I see but maybe you could optimize the way of adding scripts to NZBGet? 

Why not make it possible to "install" an extension by referencing the GitHub url? This way updating/installing scripts is really easy. The only thing to do for a script author would be adding a config file to the script that defines which files to use by NZBGet - kind of [Nuget](https://docs.nuget.org/consume/nuget-config-settings)!

All scripts (links) could also be collected in a GitHub repo and from there it is easy to have a way in NZBGet to display all available scripts and enable/disable/update them.

**Comment by hugbug** [comment]
I thought a lot about this but I came to conclusion that providing an easy way to install third-party executables is too much responsibility for me.

**Comment by jwillmer** [comment]
o.k. so maybe in a future milestone ;-)
