### ISSUE TITLE
Add nzb from directory paused

### ISSUE THREAD

**Issue by susnux** [nzbget/nzbget#233]
It would be nice to have an option to add files from nzb directory paused.

Also when using the Add dialog and enable "add paused" and then click on scan directory,
all files found should be added paused.
(For me they start immediately after scan (17 testing)).

**Comment by hugbug** [comment]
I don't want adding a special option as I don't consider it very useful and because you still can achieve this using [scan-scripts](https://github.com/nzbget/nzbget/wiki/Scan-scripts):

``` shell
echo "[NZB] PAUSED=1";
```

That will add **all** files as paused even files added via web-interface, regardless of checkbox "Add paused" in webui. That means you will not be able to add files unpaused. This is solvable as you may print the pause-command on certain conditions. For example, you can create subdirectory "paused" in nzb-directory, then check the category in scan-script and print the pause-command if category was set to "paused" (nzb-files scanned from subdirectories become category of the name of the directory).

**Comment by susnux** [comment]
Thank you scan-scripts are working.
But I was a bit disappointed when using the scan button:
I had automatic scanning disabled so I only wanted to scan manually and then I think the "add paused" Button should work?

**Comment by hugbug** [comment]
Indeed, the button "Scan incoming directory" does not take checkmark-options into account because it just initiates a directory scan which would otherwise happen on interval basis.

I agree with you that from UI design stand of point this is not clear. I don't know where to put the button otherwise.

**Comment by susnux** [comment]
I am not familiar with the nzbget internals, but would it be possible that a manually triggered scan with the checkbox enabled will add nzb's as paused?
Or would this be a lot of work to implement?

**Comment by hugbug** [comment]
That's possible but I don't like this because the scan can also happen at any time (interval scan), for example it may happen half a second before the user clicks on the Scan-button. In that case the scan initiated by the click will not find any files (all files already added) and the user may think that the checkboxes don't work properly.

**Comment by hugbug** [comment]
Closing this for the reasons explained in my previous post.
Feel free to comment or reopen if necessary.
