### ISSUE TITLE
RSS feed view in phone mode need improvements

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#263]
From forum [topic](http://forum.nzbget.net/viewtopic.php?f=10&t=2622):

> When performing a Read RSS from the main page on a mobile device portrait mode only the Titles are displayed. Could further fields be added e.g. Size, Category, Age underneath?

From other [topic](http://forum.nzbget.net/viewtopic.php?f=3&t=2621):

> When performing a Read RSS from the main page on a mobile device landsape mode the Search box appears behind the table headers. 
> 
> This means you can't touch the search box to make the keyboard appear and therefore not enter search criteria.

**Comment by guaguasi** [comment]
In regards to the landscaping issue, that only happens if (559 < width < 631). Another issue related to the responsive layout is when the RSS feed is loaded in portrait mode and then rotated to landscape, all the data is stuffed into the first table cell.

I'll look into this after I finish the changes in PR #278

**Comment by hugbug** [comment]
I consider the issue with bad formatting after rotating less important and wouldn't spent too much time on it (if it is hard to fix).
