### ISSUE TITLE
Show password-badge for nzbs with passwords

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#274]
For nzbs having password set on tab "postprocess" it would be nice to have badge "passworded", "protected", "encrypted" or similar (not sure which one) displayed in the queue and history lists.

A mouseover-hint could show the password itself.

**Comment by guaguasi** [comment]
I just did this.

How would you want mouseover-hint done? I thought about using the bootstrap tooltip, but I'd have to write a click handler and manually launch the tooltip since Bootstrap 2.0.3 doesn't have any other trigger options. The placement would also need to be changed depending on the layout. Not exactly the most  elegant, but easily doable. I could also just append `: <password>` to the label on click (and/or hover). Simplest solution would be to just add a title attribute but that wouldn't be visible on mobile.

**Comment by hugbug** [comment]
I meant the title-attribute. Doesn't work on mobile, yes, but that's just a little bonus feature for desktop.
