### ISSUE TITLE
Max download size

### ISSUE THREAD

**Issue by Darkknight33** [nzbget/nzbget#292]
I've been having an issue where my automation software is grabbing excessively large collections of files, like 80-120GB. My nzb setup isn't designed to handle downloads over about 30GB, as 99% of my downloads are smaller than that, including doubling up for extraction. This causes a huge backlog that requires a manual intervention. Part of the problem seems to stem from the fact that NZBGet doesn't do space checking on temporary storage before starting a download to see if the download will fit. 

I'd like to see an option to pause or reject (fail) any nzb larger than an upper bound, which can be manually specified by the user.

**Comment by hugbug** [comment]
This can be achieved with an extension script. If you have programming experience (or are willing to start) I could give you few pointers.

On the other side, shouldn't the automation software have a setting to limit size?

**Comment by Darkknight33** [comment]
Well, the problem is caused by trying to snatch an entire season in a single NZB. I agree that there is a fix for that, but it still doesn't stop an NZB too big for the file system being pushed from some other place to NZBGet that still breaks downloading. As long as NZBGet is willing to bite off more than it can chew, it will still break.

**Comment by hugbug** [comment]
You need to write an extension script of type **queue script** (more info in [Queue scripts](https://github.com/nzbget/nzbget/wiki/Queue-scripts)). Queue scripts are executed on certain events. You can configure your script to be executed after an nzb is added to queue. At that time the script can access nzbget using [API method "listgroups"](https://github.com/nzbget/nzbget/wiki/API-Method-%22listgroups%22), which returns info about all queued items including their sizes. Then you go through the items and look for the item which was currently added by comparing with **NZBNA_NZBID** which were passed to queue script. When you found the item you check its size and if it's too big you instruct nzbget to remove item from queue by printing a special text into standard output "[NZB] MARK=BAD".

I recommend you to write the script in python language even if you have never dealt with python. This language is very easy to learn and it works on all platform including Windows, macOS, Linux, etc. Most extension scripts for nzbget is written in python because of its cross-paltform compatibility.

Take a look at the standard script [Logger.py](https://github.com/nzbget/nzbget/blob/develop/scripts/Logger.py). It's a post-processing script. You will need to change the script signature to make it **queue script** instead. The script shows how to communicate with nzbget; it requests the log of one item from nzbget via rpc-method "loadlog", you'll use rpc-method "listgroups" instead.

Feel free to ask further question. Post your script here if it doesn't work and we'll fix it work together.

**Comment by hugbug** [comment]
Closing this for now. If you have further questions feel free to reopen and comment.
