### ISSUE TITLE
UI Refactor

### ISSUE THREAD

**Issue by rotatordisk92** [nzbget/nzbget#310]
Hi,
First of all, love your tool.

I created this issue, because I feel the UI is a little old and outdated.
I am a front end developer and was considering contributing with a complete refactor.

Maybe we can discuss?

I was thinking of building something lightweight and robust, with a beautiful design on:
React
Redux
Universal Routing
Bootstrap
MomentJS

Maybe even consider making `webui` it's own module repository.

Can we also [create a gitter channel](https://gitter.im/home/explore#createcommunity) for nzbget? So we can hold active discussions in a chat room?

Thanks @hugbug .

5punk

**Comment by hugbug** [comment]
Thanks for the offer. I could sure use help of a frontend developer and more so of a web designer.

Complete rewrite however will require months of work and years of support. Can you do that?

NZBGet exists since 2004. The webui in current form was written in 2012. At that time I was using Bootstrap as UI library. I evaluated other libs at that time too.  Bootstrap has helped a lot with beautiful controls. There is however a big issue with using external libraries - the library developers very often don't care about backward compatibility (to previous library versions), especially in JS world. You can't take Bootstrap 3 and put it over Bootstrap 2 expecting the new more modern UI. It will just not work. Hell, a simple update from Bootstrap version like 2.01 to 2.03 (I don't remember exact numbers) has broken things. I eventually decided to stick with the initial version which I was using.

Now when you want to use all that nice libraries (and frameworks which is even more scary) - are you sure they will exist in say 5 years from now? The plain JS code understands everyone. The internals of 5 years old frameworks - not so many.

My experience tells me to use as little as possible of external libraries and never use frameworks. It's sure OK to use current popular frameworks when building a new web-site for a customer, which you will not see after the job is done. But when developing for years to come it's better to stick to own code (and keep it simple if possible).

Of course I use other libraries - for example for charts - that's however parts of UI which are not core and which can be replaced if necessary (in a case current library will not work correct in a few years with newer browsers).

NZBGet webui has some unique features like very good performance, data updates without breaking of user interaction, etc.

Don't underestimate the amount of work to be (re)done. The webui has a lot of features.

---

Now, if I didn't scare you we can talk about details 😉 

What you find not modern in current UI? I hope you don't mean the internals (the fact UI doesn't use react for example) but rather from user points of UI. Too many gradients and round corners? Changing that doesn't require full rewrite.

---

NZBGet webui relies completely on API. Nothing in NZBGet core is built exclusively for webui. That means that you can put a subfolder into webui-directory and develop your own UI as an alternative. At some point we could make it default and remove the old UI. I don't like the idea of having multiple UI in a long term as this requires too much resources during further development. Still it's good to be able to switch between old and new as long as the new one isn't 100% feature complete.

**Comment by rotatordisk92** [comment]
Not at all scared :)

Can we get on Gitter? So anyone else that wants to contribute can join us there?
https;//gitter.im
Create a channel so others can weigh in with their opinions too.

This is an issue thread, since this is not a real issue we should close it.

**Comment by hugbug** [comment]
I rarely have time to chat in real time. Github issue tracker or nzbget forum or e-mail work better for me.

**Comment by hugbug** [comment]
To make a start I suggest you to create a project on github (as a separate repository), which will host the new UI and use the repository issue tracker to discuss and plan feature development and of course to track issues reported by testers and users.

Make the UI compatible with current NZBGet API. In a case your UI requires a build system - provide releases and installation instructions. Actually the installation of the UI should be as easy as putting the folder with UI files into NZBGet webui-directory. Then to access the UI you include the folder name in the URL like `http://localhost:6789/5punk`.

Every user will be able to try your UI and submit his (her) feedback via NZBGet forum or via issue tracker of your repository.

At some point in the future when your UI has matured we can include it into NZBGet package as alternative UI and then later possibly remove the old UI.

**Comment by rotatordisk92** [comment]
Sounds good!
Keep discussions alive on gitter!
