### ISSUE TITLE
Park Action Health Range

### ISSUE THREAD

**Issue by orbisvicis** [nzbget/nzbget#323]
> For dupe par-scan this is however not good because at that time usually only small part of download was downloaded. So for dupe par-scan you should disable health check. That's however stupid because the fully missing downloads will need to go to the end taking a lot of time. Therefore the folowing compromise: with "HealthCheck=park, ParScan=dupe" the health-action (park) is peformed if almost all articles (tried so far) are missing (more strictly - if completion is below 10%). As long as completion is above 10% the downloading continues, regardless of health.

This is only a cosmetic annoyance since the parked files will eventually be erased, but I'm getting quite a few  parked duplicates with a completion of 0% - nothing but empty files. If completion is <= 0.1 % perhaps nzbget should just delete the download as failed?

**Comment by hugbug** [comment]
Empty files should not be created actually.

If nothing was downloaded the directory is deleted. If something could be downloaded the directory remains, so that the command "Retry failed articles" could reuse already downloaded articles.

If you want clean up based on certain health level - maybe you could write a pp-script for that?

**Comment by hugbug** [comment]
Closing this for now. If you have more to say feel free to reopen or comment.
