### ISSUE TITLE
Cannot logout using FormAuth

### ISSUE THREAD

**Issue by frebib** [nzbget/nzbget#345]
I find myself logged into nzbget as an unprivileged user, not being able to modify many of the settings nor can I find a simple way to log out short of clearing my entire browser cache/cookies.

Using HTTP BasicAuth you can force most browsers to 're-login' using something like http://newuser@path.to/nzbget at which point it will prompt you to log in again as a different user

I cannot work out how, if at all, one can logout and back in with the improvements made in #330

**Comment by hugbug** [comment]
Login session is kept as long as browser session is running.
Close all browser windows.
Or use a new private window to login with other credentials.
Or delete cookies for the site.
Or restart nzbget (not "reload" from web-interface).

**Comment by rcdailey** [comment]
Need to bump this, because the current design is ridiculous. Add a simple log out button and be done with it. Why should I have to jump through hoops to close browser windows, clear cookies/cache, restart my servers, just to get a logout function? It's crazy!

Literally every online web application that authenticates users has a logout function. I do not believe this issue was opened because we want a work around, or that it can't be functionally done, but because we need a simple button to log out, so we don't have to do all this complicated stuff that requires sudo access and browser restarts that interfere with other activities not related to NZBget.

Sorry if I sound frustrated, but it's because I am. And I just can't believe that the developer response is so negligent on such a simple matter.

@hugbug: Kindly request that you reopen & reconsider.
