### ISSUE TITLE
Update Windows Components

### ISSUE THREAD

**Issue by wtf911** [nzbget/nzbget#368]
I was playing around with compiling things and realized maybe some things could be updated, not just for the sake of updating, but because it might make things faster? :)

1. UnRAR.exe is now at version 5.40 - http://www.rarlab.com/rar/unrarw32.exe

2. I was able to compile zlib 1.2.11 to link it statically - http://zlib.net/ - Note: it appears there may be faster forks of zlib - https://www.snellman.net/blog/archive/2015-06-05-updated-zlib-benchmarks/

3. I was able to compile with static openssl 1.1.0 - it appears faster than 1.0.2 - https://mta.openssl.org/pipermail/openssl-users/2016-April/003519.html

4. I was able to substitute the GNU regex for PCRE2 statically compiled - it should definitely be faster - http://www.boost.org/doc/libs/1_34_0/libs/regex/doc/gcc-performance.html

Notes:

1. By default in openssl 1.1.0 the RC4 cipher is disabled, that is true for the libs I was able to download here https://slproweb.com/products/Win32OpenSSL.html - which means RC4 could either not be used or openssl would have to be compiled with it enabled http://openssl.6102.n7.nabble.com/How-to-enable-RC4-in-OpenSSL-1-1-0c-td69662.html

I am on Windows 10 using Visual Studio 2015. With everything above done I was able to compile nzbget.exe without needing any .dll files to be included, it is now all statically linked inside nzbget.exe and there are no new compiling warnings or errors, nzbget.exe sits at 3115kb, everything works. all said and done with the .dll files removed the installer ends up being slightly smaller
![image](https://cloud.githubusercontent.com/assets/5151430/25418426/bdb8436a-2a19-11e7-8345-339c02460663.png)
-----------------
compiling
-----------------
- to use openssl 1.1.0 statically I took the downloaded openssl libs from the link mentioned above and copied the ones from the static folder to the normal folder and in the project file linker additional dependencies had to replace ssleay32MT.lib and libeay32MT.lib with libssl32MT.lib and libcrypto32MT.lib

- I had to add these two libs to linker > input:
crypt32.lib
legacy_stdio_definitions.lib

- I had to put this in stdAfx.cpp of nzbget:
FILE _iob[] = { *stdin, *stdout, *stderr };
extern "C" FILE * __cdecl __iob_func(void) { return _iob; }

- to compile zlib 1.2.11 i used the project in zlib\contrib\vstudio\vc14 and ReleaseWithoutAsm as the solution (because the asm build compiled but crashed when using) and for the properties of the zlibstat project i removed ZLIB_WINAPI from the c/c++ preprocessor then i just renamed it from zlibstat.lib to zlib.lib after it was built

- for PCRE2 10.23 (regex) i used CMake and in CMake checked the box for static-runtime before generating then after compiling i edited the NZBGet Visual Studio project file in a text editor and i removed regex.lib from link additional dependencies and added pcre2-posix.lib and pcre2-8.lib to it and changed in the nzbget.h i changed include "regex.h" to "pcre2posix.h"

Let me know your thoughts please @hugbug. :) Just ideas is all. I like tinkering.

**Comment by hugbug** [comment]
**Thanks for your efforts and tips.**

Generally I prefer to invest my time into NZBGet code rather than into updating or optimizing build systems. Windows is only one of **11** platforms supported by NZBGet:
- one for Windows;
- one for macOS;
- eight for Linux for each supported CPU type (x86, x86_64, ARMv5, ARMv7, MIPSeb, MIPSel, PowerPC 500, PowerPC 6xx);
- one for FreeBSD.

My general approach is whenever possible to use the same components on all platforms.

Especially because I can't do thorough testing on each platform; on some platforms I can't even do small tests as I don't have required hardware.

If I would use different library versions on different platforms a situation may occur when something doesn't work on certain platform and I'm not even aware of this because I do most of my tests on other platforms.

## Unrar
I agree that updating unrar is generally a good thing.

However as explained above this is not as simple as "download the newer binary from rarlab and use it". That's simple for Windows build of NZBGet. But for ten other platforms I have to build it. This is substantially more efforts. I do that however time to time.

I have to read the changelog to see if there were changes to unrar (for example updating unrar just because there were changes in UI of WinRar doesn't make much sense).

I've just read it and haven't found any changes NZBGet could benefit of (no bugfixes or speed improvements for rar-archives).

## OpenSSL
I prefer to use the same version on all platforms. [Buildroot](https://buildroot.org), the build system which I use to create binaries for Linux, currently still on 1.0.2. Even when Buildroot updates their libs, for me to use the newer version of Buildroot means rebuilding (from scratch) eight build environments (one for each supported CPU type). That's a scary process as usually something goes wrong and it takes time to fix things. Even if it goes without errors that's many hours of work.

As long as there are no big issues with 1.0.2 I'll stick with it.

Thanks for the tip about RC4 in OpenSSL 1.1.0, the issue I wasn't aware of.

## Static linking
NZBGet builds for Linux use static linking because that allows to have one binary (per CPU type) that works on all Linux variants regardless of installed library versions.

On Windows however the static linking has no advantages as we can simply ship required DLLs with NZBGet. Nonetheless I do like the static linking too as it avoids dependencies.

When choosing between static vs dynamic linking on Windows I prefer to use approach recommended by library developers (if there is one). I'm not obsessed with static linking though. If I have a choice to use DLLs provided (or recommended) by library authors or to compile myself a statically linked build I prefer the first one.

## Regex
On POSIX (every system except Windows) NZBGet uses system regex library. On Linux and FreeBSD that's a GNU implementation. Why would I use on Windows something else? That's asking for problems.

Besides, regular expressions are used in NZBGet only at few places where performance doesn't matter.

## Summary
I guess this post may have disappointed you but it was written with good intentions.

**Comment by wtf911** [comment]
I was not disappointed at all! I was happy for this post. I genuinely enjoy your responses @hugbug. I enjoy learning. Your reasons make perfect sense. I have fun tinkering and seeing what is possible so I just thought I would share that with you, useful or not. It's like when you made the commits for double-click functionality, I read through the code changes to try to get an understanding of what you did to get it working so I could learn from it. Keep up the great work!
