### ISSUE TITLE
Schedule automatic updates

### ISSUE THREAD

**Issue by xconverge** [nzbget/nzbget#369]
I would like the ability to enable a setting that queries for version updates and applies them if available at a set time daily/weekly/monthly.

A flag that sets whether it can be stable or testing would also be a good idea.

This should be able to leverage the existing automatic update mechanism.

**Comment by hugbug** [comment]
I'm considering it a bad practice when a software updates without user confirmation. Furthermore at least on Windows the existing update mechanism cannot be used as it requires an UAC confirmation. To overcome this an update service running under admin account is necessary.  Neither do I want to develop such a service nor I find it a good thing in general.

What I can offer instead is a notification in web-interface about available updates. The user can then decide whether to install update or to skip it.

The notification feature has been planned for a long time but never had enough priority to be worked on. Mostly because NZBGet stable releases happen not that often (2-4 times per year) and there are a plenty of alternatives such as subsciption to nzbget announcement forum, rss feed on GitHub releases, web-services which can track changes to nzbget download page or GitHub releases page, etc.

**Comment by xconverge** [comment]
A small notification that says there is a new version would be a nice compromise then :)

**Comment by hugbug** [comment]
Implemented in #440.

**Comment by xconverge** [comment]
Thanks @hugbug!
