### ISSUE TITLE
Extension script browser & installer in nzbget

### ISSUE THREAD

**Issue by rcdailey** [nzbget/nzbget#375]
It would be great to have a "store-like" interface for finding and installing extension scripts, sort of like a linux package manager.

Some things it would do:

* Connect to a remote repository of all known "published" extension scripts and present them to users
* Each extension script would have statistics (download count, 5-star review, etc)
* Sorted viewing of available extension scripts
* Install button for each script which downloads respective files to ScriptDir in nzbget
* Remove/uninstall button to remove the script
* Automatic updates for extension scripts

Have you given any thought to this? Do you have ideas? I'm a C++ programmer so maybe I could help out (I'm not the best at web stuff though...)

**Comment by hugbug** [comment]
Repository requires maintaining and this is a job I can't commit to. This isn't a one time action but a constant work for years to come.

Another issue with central add-in stores is that users tend to trust them, which in turn means additional work for the maintainer to examine all extensions. With such system extension developers can't publish quick updates because approvals from repository maintainer are needed.

NZBGet is often runs with high privileges. Having a simple way of installing executables remotely via web-interface is a big security concern.

It's of course nice to install add-ins directly within program but I don't have resources to develop and maintain such system and I don't want to take responsibility for all scripts.

Currently users need to browse forum to find extensions. That's not so bad as they see feedback from others and responses from script author. Having a simple way to communicate for users and authors via forum helps improving script. When installing directly from program there are less chances for user's feedback.

**Comment by rcdailey** [comment]
All very good points but I feel most of these issues are present today, the
only difference is that they have to hunt down scripts and install them by
hand. But once it's installed, it's running the same way either way so I'm
not sure what additional security concerns you are talking about.

Also you could in theory keep the script repo as a git repository. This
eases the burden a little bit because users can help you maintain it via
pull requests. This also helps improve scripts and collect feedback through
GitHub issues.

**Comment by hugbug** [comment]
I don't need to maintain a repository, that's the main advantage of current "system".

My understanding is that developing a package system is a huge thing, as it needs to deal with different versions of nzbget, different versions of scripts etc. and in worst case it requires a hosted application (you mentioned ratings). 

I personally have no interest in developing and maintaining such a system but if you do want to develop it and become the store maintainer, then we sure can discuss how to go there.

---

The important point of extensions was that users can develop them themself and share with each other via forum. Sharing via store is more difficult as it requires approval.

> they have to hunt 

There is no much difference between browsing forum (the special subforum with the rule "one topic per script") and browsing store page.
