### ISSUE TITLE
Migrate forum hosting from SourceForge

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#384]
For many years NZBGet was hosted on SourceForge.net. In 2015 the code repository was migrated from SourceForge's subversion to GitHub. Soon thereafter the website was migrated from SourceForge's hosting to GitHub Pages.

The forum remained hosted at SourceForge's as GitHub doesn't offer web-hosting for dynamic pages.

All was good until last week SourceForge sent a notice about [Project E-Mail Policy Update](https://sourceforge.net/blog/sourceforge-project-e-mail-policy-update/). Starting from end of July web-application will no be able to send E-Mails anymore. That means the forum cannot be hosted at SourceForge anymore as sending E-Mails is a vital function.

**Comment by hugbug** [comment]
After evaluating alternatives the only one found was [TuxFamily.org](https://www.tuxfamily.org/) which offers free hosting for open source project.

The migration is in progress.

**Comment by hugbug** [comment]
The migration is completed.

**Comment by war59312** [comment]
I see the forums support https, but not enabled by default.

Working good with HTTPS Everywhere.

Sadly still waiting on https://github.com/isaacs/github/issues/156

**Comment by hugbug** [comment]
> I see the forums support https.

What a surprise 😲.
Now thinking about moving the whole site there :thinking:.
But I like the automatic markdown->html generation on GitHub Pages so much.

**Comment by 775671463** [comment]
RCIOL HOST– Company Relaunch Exclusive Offer



A while back we posted an offer from rciol host and let s just say that it "was met with mixed reviews. As I mentioned before I m new to," this community, but what I do know is that it s difficult to run any "small business. Sometimes you think you ve got everything figured out and" you 're ready to launch then everything just falls - and apart. I m a firm believer in "the value of learning from experiences, especially failure.

I 'm going to let what Justin sent in speak for itself:

Short Bio:
Rciol was founded March focused primarily in the 2001 and LowEnd market. We are particularly proud to offer many features that cannot often be offered by many LowEnd companies, including 24/7 support, a 90-day money back guarantee, RAID-10 disks and dual processor nodes.
Changes/More Info:
After we were first listed on rciol.com, we knew that we loved the community, but we also knew that we had some substantial changes to make, in order to ensure that customers really do have a positive experience with us. So, we took some time to regroup, and now we have prepared a re-launch of rciol, specifically addressing and fixing past issues.
Improved Support
We have increased our support availability to be 24/7/365, and we are now offering live chat support during day. the business
New Locations
YourLastHost is now operating out of three distinct locations, South Korea, Hongkong, the United States, Taiwan. With such a diverse set of options, your customers are never far away from us.

Dedicated Servers-USA
ATOM
2 GB
500G SATA3
100M1Gbps
$89.00
Free Setup
Order Now:http://whmcs.rciol.com/cart.php?a=add&pid=12

Dedicated Servers-Korea
E5507X2
4 GB1TB 
SATA3
10M
$80.00
Free Setup
Order Now: http://whmcs.rciol.com/cart.php?a=add&pid=18

Dedicated Servers-Hongkong

ATOM
4 GB
1TB 
SATA3
5M
$140.00
Free Setup
Order Now: http://whmcs.rciol.com/cart.php?a=add&pid=9



Dedicated Servers-Taiwan
E5200
2 GB
500G SATA3
10M
$220.00
Free Setup
Order Now: http://whmcs.rciol.com/cart.php?a=add&pid=21
