### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by rcdailey** [nzbget/nzbget#413]
There is a dark theme on userstyles here: https://userstyles.org/styles/132287/nzbget-dark

Can we get this incorporated into NZBget directly?

**Comment by hugbug** [comment]
Probably but the theme needs extra work as it has following flaws at the moment:
- it's way too high contrast;
- here and there wrong colours;
- modal dialogs look very bad: no border, dark background effect doesn't work here due to black background; I don't know what would be a proper solution here.

When this is fixed someone has to integrate it into NZBGet in a way similar to how phone theme works: to activate the theme the "body" of the page will get class "dark" added and all CSS rules for the theme must have ".dark" in the selector.

The theme should work properly in major browsers on desktop (Chrome, Firefox, Safari, Edge) and mobile (Safari on iOS, Chrome on Android).

I can accept a PR but I can't do all that work myself.

It would be also nice if the author of PR can support the theme in the future - test the theme before new stable releases and fix issues if necessary.

**Comment by ghost** [comment]
Hi, I'm the author the userstyle: https://userstyles.org/styles/132287/nzbget-dark
Thanks hugbug for your constructive criticism, I made some changes. 

I agree with rcdailey that it would be great to have a dark theme implemented in NZBGet.
I just created this userstyle to reduce my eye stress caused by to much brightness.
But, I'm not a web developer and neither have time to contribute in a big project like this.

Plus NZBGet uses a deprecated version of bootstrap (v2).
If migrated to v3 (soon v4), light and dark themes can be easily chosen (ex: flaty and darkly)

I don't know if elycharts can be styled with CSS but I failed to do it.
If that's not possible then change the lib (ex: highcharts).

SASS would be a nice addition as well.

**Comment by hugbug** [comment]
Thanks for your feedback @enren.

Unfortunately Bootstrap versions are not backward compatible. Migrating to a next version requires an incredible amount of UI rewrite. Not gonna happen just because of dark theme. Developing and supporting own dark theme is a much easier (although big too) task compared to migration.

**Comment by hugbug** [comment]
Closing this. If anyone wants to participate please post a comment.

>I can accept a PR but I can't do all that work myself.
>It would be also nice if the author of PR can support the theme in the future - test the theme before new stable releases and fix issues if necessary.

**Comment by isarrider** [comment]
just for reference...
I changed my to dark, can be seen as a draft...
[style.txt](https://github.com/nzbget/nzbget/files/5931192/style.txt)
(rename to style.css)
