### ISSUE TITLE
nzbget.net/info/nzbget-version.json isn't valid JSON

### ISSUE THREAD

**Issue by frebib** [nzbget/nzbget#415]
I'd open an issue on the `nzbget.github.io` however it's not available.

The opening line, more specifically the assignment before the open brace makes the JSON invalid and unparseable by most JSON parsers.

```
NZBGet.VersionInfo = {
    ....
```

Perhaps you could consider removing it or providing an alternative page with valid JSON data.
Cheers

**Comment by frebib** [comment]
This applies to all instances of this file, for each OS available.

**Comment by hugbug** [comment]
The header is added to make it json-p compatible, for easier usage on web-pages. If you are in a comfort situation of being able to process the response in a code you control then you certainly can strip the header before feeding the parser.

**Comment by frebib** [comment]
Unfortunately we're in the situation where we can pass a URL to a JSON file and the path to the string within the object, as such: `."testing-release"` however the malformed JSON causes an error.
Is there possibility of being able to send a header or a page argument to strip the header on the server side?

**Comment by hugbug** [comment]
This is static hosting. No server side coding possible.

Can't you process the file as a text file using (for example) regular expressions?

I'm curious what project needs this info?

**Comment by Adam-Ant** [comment]
Hello, jumping in here as I'm working on this project with frebib! The data is being used as part of a continuos integration pipeline. We use [Drone](https://github.com/drone/drone) to build and publish Docker images, [including one for Nzbget](https://github.com/Adam-Ant/docker-nzbget). Drone triggers build based on Webhooks, such as those sent by GitHub when a new commit or release is pushed.

Obviously we cannot add webhooks to projects we can't control, such as Nzbget. So to work around this we have built a program that takes an arbitrary JSON tag as an input, and when it detects a change it triggers a build. This program is DroneTrigger, and can be found [here](https://github.com/Adam-Ant/drone-trigger). Since we want to trigger seperate builds based on the Testing and Stable branches, we need somewhere where we can monitor for version changes for both, hence the use of the nzbget-version.json file.

The json file on the NzbGet website seems to not be proper JSONP either though. I will admit I am not that familiar with the standard, but all other examples of it I can find wrap it in brackets, [like this](http://run.plnkr.co/plunks/v8xyYN64V4nqCshgjKms/data-2.json), instead of the equals yours uses.

**Comment by hugbug** [comment]
I think you have fixed this on your side, right?
