### ISSUE TITLE
make direct unpack cancel only if a rar volume is incomplete

### ISSUE THREAD

**Issue by itouch5000** [nzbget/nzbget#427]
In this [NZB](https://nzbindex.com/release/157636749/8xsfsmtw8zccedeujk4rv6a-001107-8xsfsmtw8zccedeujk4rv6a.par2.nzb) only the last par2 volume is incomplete but direct unpack still cancels. This volume is actually not necessary for direct unpack. Is it possible to cancel direct unpack only if a rar volume is incomplete?

**Comment by hugbug** [comment]
Direct Rename (which Direct Unpack builds upon) needs data from every file to handle the whole file set properly. In certain cases even damaged files can be processed properly but that requires special handling for each case.

The code is already complex enough. I've tried to implement special handling for a case represented in your nzb-file but that's way too complex and isn't worth it because I believe cases like that (damaged only par-files) are very rare.
