### ISSUE TITLE
Offload post-processing to another computer / server running NZBget?

### ISSUE THREAD

**Issue by RollingStar** [nzbget/nzbget#43]
I have NZBget running on some older hardware. Downloads work fine but unrar / unpack takes a bit of time. PAR repair can take extremely long, over 30 minutes, depending on how many files need to be repaired.

I have a faster computer on the same local network. Cat 5e speeds should be enough to transfer PARs and RARs between the two quickly, for processing and sending back to the slower PC to write the finished file locally.

Some users use NZBget on very slow hardware, like the Raspberry Pi. It would greatly improve speeds for those users.

Does this exist yet? Could it exist in the future?

**Comment by hugbug** [comment]
Set option **ParTimeLimit** to cancel repair if it will take too long. When the download fails (due to cancelled par-repair) you can do par-repair on another computer using QuickPar or par2cmdline. After repair use command "Post-process again" to post-process the item.

This is however for rare situations (because manual intervention is required). If you are not satisfied with unpack speed you probably need better hardware. 30 minutes for repair isn't that bad actually, especially if that happens overnight when you sleep. For occasional urgent downloads you can use the program on PC (NZBGet or other program).

Distributed post-processing doesn't exist in NZBGet and isn't planed. This feature has low-demand but is very complex and error prone.

**Comment by RollingStar** [comment]
Fair enough.
