### ISSUE TITLE
PAR: Failure -> files stay on disk

### ISSUE THREAD

**Issue by sasha-koss** [nzbget/nzbget#436]
When a download fails with PAR:Failure it stays in InterDir until you manualy delete the history, this fills up my hdds pretty quick. Is there a way to automaticly delete files from disk with said status?

Status:
https://pasteboard.co/GId4aaw.png

System:
20.0-testing-r2075
Win 8.1 64Bit

**Comment by hugbug** [comment]
The reason files stay is because you may want to retry post-processing, for example if you found extra par-files. There is also function "Retry failed articles" which you can use after adding another news server to your config or if the failure was pcaused by propagation issues.

Anyway the files are deleted automatically after **KeepHistory** days, which you can adjust.

**Comment by sasha-koss** [comment]
My InterDir HDD has about 150GB of free space, that runs full in under a day with PAR-Failed downloads if i add a new series to sonarr.
If i set KeepHistory to 0, sonarr can't check the status of the download and blacklist the nzb.
A Checkbox for keep PAR-Failed Archives would good to have with this kind of setup.

**Comment by hugbug** [comment]
You can delete files in a post-processing script if you want.

Although the real problem here is that your HDD is too small for your download volumes.

**Comment by sasha-koss** [comment]
My destination volume has more than enough space, but the intermediate HDD does not.

I used the intermediateDir function today for the first time to test DirectUnpack.
The first problem i had was HDD I/O's bottlenecked performance, thats why i used the interDir.
My understanding was that the interDir is just tempory and that all fails - even failed Pars - would be stored in destDir.

A PP Script to always move all files form interDir to destDir would make sense, thanks for the idea.

Edit: Would the KeepHistory Setting remove the moved files?

**Comment by hugbug** [comment]
I also wonder why do you have so many par-failures. Dmca'ed downloads are usually gone completely and no files remain in InterDir.

I meant a pp-script to delete files. Why move them if you don't care about retries?


DestDir is for successful downloads. Files remain in InterDir also because they will be deleted soon, why spend time moving broken files which user will later need to delete.

**Comment by sasha-koss** [comment]
Most of the downloads fail the health check and get deleted, but today i had many at 99%/100% that failed par-check and clogged my interDir HDD.
It's definitly not a daily use Problem, but can occur when Netflix releases a whole new season.

Pastebin for more detail:
https://pastebin.com/uJ2crj2y

**Comment by hugbug** [comment]
> Would the KeepHistory Setting remove the moved files?

It should, if your script inform the program about new location: https://nzbget.net/post-processing-scripts#control-commands.

**Comment by sasha-koss** [comment]
Thanks for the fast reply and pointing me in the right direction, i'll (try to) write me pp script.
Best Regards
Sasha

**Comment by hugbug** [comment]
99% health and failed? Interesting. Were par-files there at all? If par-files were missing in nzbs that would mean the nzbs were badly constructed (indexer's fault) and may be you should report this to indexer.

You could also try to find missing nzbs par-files on search engine, download and put them into nzb's InterDir, then use "Post-procss again" to retry repair. Although that can be too much effort if you have alternative sources and quick connection.
