### ISSUE TITLE
Faster CRC32 computation

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#446]
One part of download process is computation of checksum (CRC32). It takes about 3-10% of CPU time. Currently NZBGet implements classic algorithm for CRC computation. There is a number of alternatives faster algorithms. A nice overview can be found here - [Fast CRC32](http://create.stephan-brumme.com/crc32/).

By changing of CRC algorithm we can reduce CPU usage to the third.

**Comment by Safihre** [comment]
Why not slice by 8? Or 16? Or use the Intel-SSE version which is even faster? I was also looking at these :)
https://github.com/animetosho/node-yencode/blob/master/crc_folding.c
In the end I just removed CRC checking completly, since after much testing it turns out if the CRC is not correct, usually the length of the article is also much shorter. It's not just 1 char that flipped, but whole sections missing. So simple length-check is enough. I never actually saw that in real life NNTP downloads from any server.

Maybe you already saw that we were considering using SSE/SIMD functions for yEnc decoding? Still concept stuff for now, but probably code you could implement very quickly and efficiently, compared to me 😉 
https://github.com/animetosho/node-yencode/issues/4

**Comment by hugbug** [comment]
> Why not slice by 8? Or 16?

In my short tests they performed with the same speed in NZBGet; so I've took the smaller one. I admit I tested only on my machine but in tow modes x86 and x86_64. I should probably do more testing.

> Or use the Intel-SSE version which is even faster?

That's a tricky thing. I've just tried this on my machine and it failed to compile. Googled that PCLMULQDQ instruction and it turned out my CPU doesn't support it. What would happen if it would support the instruction? I would be able to compile but the program would crash on machines with older CPUs. So to use that implementation properly the program need to examine the CPU type and then use the fast or the classic routine. Not so easy as you see.

### ARM
I've just made more testing on ARM machine. Tested multiple times with 4GB nzb downloading from NServ running on another machine. The numbers are download speed (MB/s) and download time (s):
- CRC **disabled**: 45.2MB/s (46s), 47.3MB/s (44s)
- CRC new routine **slice-by-4**: 46.2MB/s (45s), 43.3MB/s (48s)
- CRC old routine **classic**: 42.4MB/s (49s), 39.2MB/s (53s), 40.8MB/s (51s)

The download speed is calculated based on download time in seconds which is an integer value; fractions of seconds can not be measured here unfortunately.

As you see the new routine performs very well here and adds little overhead compared to disabled CRC.

### x86_64
On (old) x86_64 machine the numbers were:
- CRC **disabled**: 156MB/s (28s), 156MB/s (28s)
- CRC new routine **slice-by-4**: 141MB/s (31s), 141MB/s (31s)
- CRC old routine **classic**: 141MB/s (31s), 145MB/s (30s)

Here there is still a big lap between no-CRC and new routine. However the speed is already higher than anyone can get on an Internet connection. That's old PC. On a newer one I get numbers in 250-300MB/s range. Even if I can get extra 10-20MB/s that doesn't really matter. Although out of sport interest maybe ;)

The code which use newer CPU instructions is difficult to integrate and maintain. I would be more interested in optimisations for ARM because x86 already fast enough for any real usage.

---

Very interesting discussion regarding yEnc. I'll post my thoughts there.

**Comment by Safihre** [comment]
@hugbug Thanks for that feedback, I did not test its that extensively but just read about it :)

Indeed runtime detection of CPU capabilities would be required, but there are header files for that.
ARM has NEON, which should allow semi-interchangeable intrinsics form x86 ones, as far as I understand. But you probably understand the particulars much better!

**Comment by hugbug** [comment]
> But you probably understand the particulars much better!

Not at all. SIMD programming is a black magic to me :dizzy:

**Comment by sanderjo** [comment]
> Not at all. SIMD programming is a black magic to me :dizzy:

I think SIMD programming is black magic - or at least magic - to everybody ... which makes it so cool ... ;-)

**Comment by animetosho** [comment]
`PCLMULQDQ` requires a CPU with AES-NI support. [This is available](https://en.wikipedia.org/wiki/AES_instruction_set#Intel_and_AMD_x86_architecture) on all Intel CPUs after (and including) Westmere (2010), except for the low end, non-Atom, Celeron/Pentium branded CPUs (because Intel likes to be super annoying with their product segmentation). On the AMD side, anything after, and including, Bulldozer (2011) has AES-NI support.  
I expect there to be a reasonable amount of support amongst users (according to the [Steam Hardware Survey](http://store.steampowered.com/hwsurvey), 79.02% of users have AES-NI at time of writing), but those running an Intel Core 2, AMD K10 (Phenom) or earlier won't have support for the instruction.

Be aware that different CPUs can have vastly different performance characteristics, just to make life difficult. What CPUs are you testing on?

> So to use that implementation properly the program need to examine the CPU type and then use the fast or the classic routine.

Correct - dynamic dispatching needs to be implemented to support CPUs with different instruction extensions. On x86, there's `CPUID`. ARM, unfortunately, seems to be another ball game, as it doesn't expose something similar to userland applications. From a quick search, it seems that methods used to implement runtime CPU detection include attempting to execute instructions and catching SIGILL exceptions.

Speaking about ARM, ARMv8 includes an optional CRC extension (which is mandatory in ARMv8.1). If this instruction isn't available, there's a `PMUL.P8` (or whatever the correct mnemonic is) NEON instruction which can be used to accelerate CRC calculations, though I've never tried it.
