### ISSUE TITLE
r2147 crashes with exit code 0 with grsec kernel

### ISSUE THREAD

**Issue by frebib** [nzbget/nzbget#464]
As of the latest build, nzbget starts and instantly exits with 0 running on Alpine Linux. The previous build r2108 doesn't exhibit this behaviour.

We are building nzbget into an Alpine Linux Docker container and our CI has been failing builds since the latest testing release. The CI runner processes are running in Alpine Linux VMs. Building the container on my computer running Arch doesn't exhibit this behaviour easier.

I have a hunch that this could be due to the `linux-virthardened` kernel that Alpine runs by default- I'll try to do some testing on this ASAP. I wonder if this is caused by the glibc change?

Here is the latest failed build: https://drone.adam-ant.co.uk/Adam-Ant/docker-nzbget/30
Here is a test build I ran with r2108 which passes: https://drone.adam-ant.co.uk/Adam-Ant/docker-nzbget/31

**Comment by frebib** [comment]
Here is a working example to reproduce the issue. This only works on my Alpine Linux VM; running on my Arch box they both load fine as would be expected.

```bash
git clone https://github.com/Adam-Ant/docker-nzbget.git
cd docker-nzbget/
# Build the image with two builds to test
docker build -t nzbget-dev:r2108 --build-arg NZBGET_URL=https://github.com/nzbget/nzbget/releases/download/v20.0-r2108/nzbget-20.0-testing-r2108-bin-linux.run .
docker build -t nzbget-dev:r2147 --build-arg NZBGET_URL=https://github.com/nzbget/nzbget/releases/download/v20.0-r2147/nzbget-20.0-testing-r2147-bin-linux.run .
# Run each and observe exiting behaviour
docker run -v $PWD/config:/config nzbget-dev:r2108
# ...runs as expected
#[INFO] nzbget 20.0-testing-r2108 server-mode
#^C[INFO] Stopping, please wait...
sudo rm -rf config
docker run -v $PWD/config:/config nzbget-dev:r2147
# Created default config file at /config/nzbget.conf
# ...prints nothing then exists

**Comment by frebib** [comment]
I can confirm that within Alpine Linux, nzbget installed using the installer, not running in a Docker container and running the `linux-vanilla` kernel this is not an issue and runs as expected on version r2147. I will try building a debug build now to attempt to find the issue

**Comment by frebib** [comment]
...aaand a fresh debug build doesn't crash even running in `linux-hardened`

**Comment by hugbug** [comment]
Can this be reproduced without docker in some VM?
To setup a VM which iso from many offered on Alpinelinux.org download page should I take?

**Comment by frebib** [comment]
Yes I reproduced this in an Alpine Linux VM using the install script straight in the VM.
Using the 'virtual' version: http://dl-cdn.alpinelinux.org/alpine/v3.6/releases/x86_64/alpine-virt-3.6.2-x86_64.iso

It must be an incompatibility with grsec

**Comment by frebib** [comment]
(as a sidenote I'm struggling to [build the toolchain](https://github.com/nzbget/nzbget/blob/develop/linux/build-info.txt) to do a complete debug build so until I have that working I can't do much more testing)

**Comment by hugbug** [comment]
Debug builds are provided in release section on GitHub.

**Comment by hugbug** [comment]
1. I can reproduce the issue in VM.
2. Interesting the 32 Bit version starts without issues. It was installed with: `sh nzbget-latest-testing-bin-linux.run --arch i686`
3. 64 bit version works to some extent:
   - commands `./nzbget -v` and `./nzbget -h` work;
   - remote commands such as `./nzbget -L` or `./nzbget -G 10` work too when connecting to 32 bit daemon;
   - remote command `./nzbget -C` doesn't work.

I don't know how to debug this. `gdb` cannot run executables, for both 32 and 64 bit binaries it prints:
> warning: Cannot call inferior functions, Linux kernel PaX protection forbids return to non-executable pages!
> Warning:
> Cannot insert breakpoint -6.
> Cannot access memory at address 0x8eb8e0

However `gdb` can start nzbget 19.1. Most likely the issue is indeed caused by glib.

**Comment by frebib** [comment]
A quick google reveals this could be a solution to make `gdb` work: 

`setfattr -n user.pax.flags -v "emr" /usr/bin/gdb`

**Comment by frebib** [comment]
Ok it seems to be a GRsec issue. Running this command (I have no idea what it does) on the binary allows it to be debugged and also run:

`setfattr -n user.pax.flags -v "emr" path/to/nzbget`

**Comment by hugbug** [comment]
After 
```
setfattr -n user.pax.flags -v "emr" nzbget
```
it started to work!

So what is this?

**Comment by frebib** [comment]
I've never really used grsec before (and I don't plan on it now..) but it looks like stricter memory management. Whatever the libc change did, it affected something that triggers this.
I'm not sure if it's an issue however.

**Comment by hugbug** [comment]
Is this issue affecting only your build system or also users of the container?
Can container script set the attribute after nzbget installation? Although after update via web-interface the flag will probably be gone.

**Comment by frebib** [comment]
Only the build system but I have no issues with changing the kernel to `linux-vanilla`. I'm more interested in why it's crashing as it looks like something in a non-executable memory page is trying to be executed. I think the extended attributes can be set but I'm not sure if they'll stick around in the container filesystem (`tar` I believe). This in theory would affect anyone running nzbget on grsec

**Comment by frebib** [comment]
It looks like (for the most part) extended attributes are supported in most docker filesystems: https://github.com/moby/moby/issues/20331

**Comment by hugbug** [comment]
I've compiled r2148 with glibc and uclibc. The uclibc binary works immediately whereas glibc binary exits.

So that is official now: the problem is definitely related to glibc.

Maybe there is a way to compile glibc with certain options to fix the issue?

**Comment by hugbug** [comment]
Is there perhaps some log file from grsec which would give us a hint which part of nzbget/glib causes the exit?

**Comment by frebib** [comment]
It seems that nzbget alone doesn't trigger any logging from the kernel but gdb does when crashing with the `Cannot call inferior functions, Linux kernel PaX protection forbids return to non-executable pages!` error:

```bash
nzbget-test:~/nzbget# ./nzbget -s

nzbget-test:~/nzbget# dmesg
nzbget-test:~/nzbget# gdb -tui
nzbget-test:~/nzbget# dmesg
[18297.231267] PAX: From 10.185.121.10: execution attempt in: <anonymous mapping>, 7f1a2d4de000-7f1a2d69f000 7f1a2d4de000
[18297.231271] PAX: terminating task: /usr/bin/gdb(gdb):26088, uid/euid: 0/0, PC: 00007f1a2d4de000, SP: 00007ffca0d42dd0
[18297.231272] PAX: bytes at PC: cc 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[18297.231280] 
[18297.231281] PAX: bytes at SP-8: 00007f1a2d4de000 00007ffca0d42de0 00007f1a2d45538a 0000000000000000 0000000000000000 0000000000000000 00007f1a2d4681c3 00007f1a2d6a2b90 0000000000000000 0000000000000007 00000000000065e6 
[18297.231286] 
[18297.231298] grsec: From 10.185.121.10: denied resource overstep by requesting 4096 for RLIMIT_CORE against limit 0 for /usr/bin/gdb[gdb:26088] uid/euid:0/0 gid/egid:0/0, parent /usr/bin/gdb[gdb:26083] uid/euid:0/0 gid/egid:0/0
[18297.231311] grsec: From 10.185.121.10: bruteforce prevention initiated for the next 30 minutes or until service restarted, stalling each fork 30 seconds.  Please investigate the crash report for /usr/bin/gdb[gdb:26088] uid/euid:0/0 gid/egid:0/0, parent /usr/bin/gdb[gdb:26083] uid/euid:0/0 gid/egid:0/0
```

**Comment by Prinz23** [comment]
https://stackoverflow.com/questions/35591704/docker-and-pax-host

> PaX mandates that executables that require to create new memory pages containing code be marked with either special ELF headers or extended filesystem attributes, preferably both, because the recommended setting for Gentoo is to use the extended attributes and ignore the ELF headers. Executables that don't comply get killed the moment they try.

So i guess the code is not marked that way in glibc.

**Comment by hugbug** [comment]
NZBGet could not create threads. The functions which don't require new threads worked OK.

When glibc creates new threads it configures stack memory with attribute `executable`. PaX doesn't like this.

I've developed two solutions. First was to override `glibc` global variable `_dl_stack_flags` at runtime. Glibc uses that global variable to control flags for new stacks, we can remove `PF_X` flag. At program start:
```C++
#ifdef __GLIBC__
	// We don't need executable stack: removing PF_X flag to improve compatibility with hardened kernel
	extern unsigned short _dl_stack_flags;
	_dl_stack_flags &= ~1;
#endif
```

That solution worked but I didn't like it for following reasons:
- access to `_dl_stack_flags` is possible only with static linking. That's what we do in universal installer builds but for someone compiling nzbget manually the program is usually linked dynamically and the build fails at linking stage. To overcome this we need a way to configure the program either for dynamic or static linking.
- `_dl_stack_flags` may not be accessible in newer or older glibc versions or it may behave differently.

The second solution was to patch glibc and modify stack allocation routine to remove executable-attribute. No changes in NZBGet source code is needed.

I chose the second approach as it's more clean and I can better control the build environment. Only universal builds for architectures which use glibc (currently x86_64 and armhf) are affected. The patch is documented in toolchain build instructions.

The fix is already applied and will be included in the next testing release.

**Comment by frebib** [comment]
Holy crap, good work detective!
I'll get on trying that out :)

Thanks!

**Comment by hugbug** [comment]
In a case you want to test it - [here](https://drive.google.com/file/d/0BwVEk7OME18vVzBvbkVQUzJVY1U/view?usp=sharing) is the new build.

**Comment by frebib** [comment]
Works a treat, thanks very much!
