### ISSUE TITLE
Armhf binaries does not work on Rpi3/ArchLinux

### ISSUE THREAD

**Issue by ggtools** [nzbget/nzbget#480]
I set up a couple of days ago a Rpi3 with the latest version of Arch Linux 64 bit. While a comment from @hugbug in issue #418 suggests that armhf binary should work on aarch64 they are definitely now working on my set.

## My box

```
$ uname -a
Linux rpi-02 4.13.10-1-ARCH #1 SMP Fri Oct 27 19:00:27 MDT 2017 aarch64 GNU/Linux
```

For both versions, I retrieve the binaries through the universal installer yesterday (November 22nd 2017)

## Version 19.1

```
$ md5sum nzbget
6eeb462e9125d41c9bad17619c883b0b  nzbget
$ file nzbget
nzbget: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped
$ ./nzbget
bash: ./nzbget: cannot execute binary file: Exec format error
```

## Version 20.0 (testing)

```
$ md5sum nzbget
45364cf91ee7099ef286acc9651f6c56  nzbget
$ file nzbget
nzbget: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, for GNU/Linux 2.6.32, stripped
$ ./nzbget
bash: ./nzbget: cannot execute binary file: Exec format error
```

**Comment by hugbug** [comment]
Looks like your Linux can't execute 32 bit binaries.

What does command `ldd /path/to/nzbget` print?

**Comment by ggtools** [comment]
Yes that's probably a specificity of arm64 Arch Linux. 

```
$ ldd ./nzbget
        not a dynamic executable
```

**Comment by hugbug** [comment]
The idea with `ldd` wasn't that smart because nzbget is indeed not a dynamic executable (statically compiled).

It seems Linux kernel has a so called compatibility layer allowing running 32 bit executables on 64 bit kernel. As everything in Linux that feature is configurable. The kernel you use probably doesn't have the compatibility activated. The config option is called `CONFIG_COMPAT`. From my understanding the option must be activated during kernel compilation. Therefore you cannot activated it unless you compile the kernel yourself.

Maybe you could clarify that with Arch Linux support? What was the reason to deactivate the option? Maybe they provide multiple kernels and you could install another one with compat?

**Comment by sanderjo** [comment]
... or make/build nzbget yourself, which will give you a 64-bit nzbget, which will thus work on your 64-bit-only system.

**Comment by sanderjo** [comment]
and out of curiosity: does this work? Just to see what value of CONFIG_COMPAT was used?

`zcat /proc/config.gz | grep CONFIG_COMPAT=`


On my own ARM64 I can run 32-bit:
```
sander@nanopineo2:~$ zcat /proc/config.gz | grep CONFIG_COMPAT=
CONFIG_COMPAT=y

```

**Comment by ggtools** [comment]
@sanderjo you nailed it

```
$ zcat /proc/config.gz | grep CONFIG_COMPAT
# CONFIG_COMPAT_BRK is not set
# CONFIG_COMPAT is not set
```
Beside I did manage to build a dynamic version for 19.1 but I'm still struggling to create a static version.

**Comment by ggtools** [comment]
Out of curiosity also what distribution did you installed on you box?

**Comment by sanderjo** [comment]
> Out of curiosity also what distribution did you installed on you box?

I have armbian Ubuntu running on my NanoPi NEO2. Which is a very nice combination, IMHO.

**Comment by hugbug** [comment]
> Beside I did manage to build a dynamic version for 19.1 but I'm still struggling to create a static version.

If you compile for (on) a specific system you don't need the static version. I provide static builds in order to avoid dependencies on other libraries; that makes binaries compatible with a wide variety of Linux distributions.

BTW Arch Linux maintainers are quick in updating their nzbget package. It usually takes only a couple of days after nzbget stable is released for it to be available in Arch repository.

---

I could provide binaries for **aarch64**. There were an issue with aarch64 which has been solved in v20 after switching from uclibc to glibc. The reason I didn't provide arch64 binaries yet was that armhf binaries worked just fine on aarch64 and my benchmarks shown no big advantage of aarch64 binaries.

Every additional architecture means more maintenance work in future. That's why for example I don't have specific binaries for each Intel CPU but rather only for two archs: x86 (i686) and x86_64 (core2).

Aarch64 is an important architecture. If the problem is wide spread I shall add native aarch64 support.

It would be nice if you could clarify with Arch Arm Linux maintainers if armhf binaries are not supported on purpose or if they possibly could enable its support.

**Comment by ggtools** [comment]
I just asked on the forum it there's any specific reason about this.

Anyway, no problem about this, I was merely trying to create a Docker image similar to [this one](https://hub.docker.com/r/lsioarmhf/nzbget/) but working on my Rpi. So a static binary would have helped not to have complex Dockerfile but if it turns out that building a static executable is too complicated I'll try multi-stage build and that should be ok.

**Comment by sanderjo** [comment]
> I just asked on the forum it there's any specific reason about this.

Can you post the link to your forum question, so that we can follow?

**Comment by ggtools** [comment]
It's here: https://archlinuxarm.org/forum/viewtopic.php?f=65&t=12285

**Comment by sanderjo** [comment]
@hugbug 

As long as the installer only has the 32-bit ARM version (which I can understand for now), you could check on 64-bit ARM systems if that system/OS supports running 32-bit with the method. And if not, do not install the 32-bit version, and clearly report to the user?

```
sander@nanopineo2:~$ uname -ip
aarch64 aarch64

sander@nanopineo2:~$ grep CONFIG_COMPAT= /boot/config-$(uname -r)
CONFIG_COMPAT=y
```
... meaning it does support 32-bit-exes.

**Comment by hugbug** [comment]
> It's here: https://archlinuxarm.org/forum/viewtopic.php?f=65&t=12285

Still no reply from Arch Linux Arm developers. Maybe that platform isn't used at all?
