### ISSUE TITLE
Add ability to set default sort order

### ISSUE THREAD

**Issue by unikitty37** [nzbget/nzbget#486]
Currently, the downloads list appears to be sorted by the order items were added to the queue, regardless of priority — so it doesn't show the order in which downloads will occur.

I can click on the 'P' to sort by priority, but this doesn't stick — if I click on History and then on Downloads, it's back to being sorted by order added again.

Would it be possible to either have a setting for default sort order, or to make NZBGet remember the sort selection, so that it's the same each time I come back to the downloads list?

Thanks

**Comment by Nothing4You** [comment]
If you change the sort by it changes the order in which items will be downloaded. E.g. if you click sort by size it'll load the files starting at the smallest ending with the largest or other way round. It will completely change your download order. The only thing that /might/ be an option here would be sorting by priority, however, you can change priority which will change the download order again.

Imagine this:

FileA - Normal
FileB - High
FileC - Normal
FileD - High

Initial download order will be B-D-A-C. Now you sort by prio and it'll be B-D-A-C in the list.
Now you change the prio of A to High aswell, however, since A is behind B and D already it'll get downloaded as third instead of right away since you sorted the others before A.

**Comment by unikitty37** [comment]
I'm slightly confused — what I want there is for the list to always show in the order in which things will be downloaded, like SABnzbd did — so in your example, it's correct for the list to remain as B-D-A-C, as A will be downloaded third. If, instead of A, you'd changed the priority of C to High, I'd want the list to change to B-D-C-A.

The behaviour that I get when clicking on P is correct — but if I reload the page or change tab, it switches back to displaying the list in the order items were added to it, and I have to click P again to get sorting by priority. All I want is for nzbget to remember that I've changed the sort order when I click back to the download list.

**Comment by Nothing4You** [comment]
My point is that the order you see is the order nzbget will process the files (except for priority jobs being preferred, still within the same prio in the order they're in the list). It's not detached from the internal queue order. If you manually reorder them to be D-C-B-A it will download D-B-C-A due to priority.
If you currently change the prio of C to high the order will be B-C-D-A, not B-D-C-A, since C is earlier in the list than D.
I can't currently check the persistence of ordering by prio, however, in the past when I've tried ordering by other columns that order stayed for all files that are already in queue, however, it won't affect new files. It's just modifying the queue, not actually applying some visual-only order.

**Comment by hugbug** [comment]
> The behaviour that I get when clicking on P is correct — but if I reload the page or change tab, it switches back to displaying the list in the order items were added to it, and I have to click P again to get sorting by priority. All I want is for nzbget to remember that I've changed the sort order when I click back to the download list.

That's not correct. The order of items is preserved. The newely added items will be added to the end of queue though.

**Comment by hugbug** [comment]
You may find that extension script useful - [QueueSort - automatic queue sorting](https://forum.nzbget.net/viewtopic.php?f=8&t=1798&p=15711).

**Comment by unikitty37** [comment]
Thanks — that's doing what I want.

It doesn't trigger when I change the priority on an existing item, though — is there a way to manually run it, or hook it to that event as well?

**Comment by hugbug** [comment]
> is there a way to manually run it

You don't have to run it manually, instead click on the priority column in web-ui.

**Comment by mrmachine** [comment]
Regardless of the nitty gritty technical details, I'm also frustrated that the Downloads queue doesn't just always, automatically, by default, show me what's *actually* downloading now and what's *actually* going to download next (force priority). I am forever clicking P every single time I view this page. Surely there's some way to configure nzbget to do this automatically on page load and when new items are added to the queue?
