### ISSUE TITLE
postprocessor should try all *.rar files

### ISSUE THREAD

**Issue by aerickson** [nzbget/nzbget#508]
Some usenet nzbs I've downloaded have included multiple .rar files. nzbget will often select the 'bad' rar that doesn't contain any content (or the content desired) and the postprocessor will fail with an error like:

```
Unrar: WARNING: You need to start extraction from a previous volume to unpack REDACTED.mkv
```

The second rar file often works, but nzbget only considers the first matched rar file.

It would be great if nzbget would try all *.rar files.

**Comment by hugbug** [comment]
It does unpack all files. The error you get means some rar-files are missing. If you think the error is printed mistakenly please post the whole log of that nzb - click on history item, then on button "Log", then " Save to file", upload to pastebin.com.

**Comment by aerickson** [comment]
Uploaded to https://pastebin.com/4HXVU3pV.

When I inspect the download in the inter directory, it has 2 rar files. The media file is in 'redactednzbtitle.rar', not 'RedactedNzbTitle.rar' (verified by manually unraring).

```
> ls *.rar
redactednzbtitle.rar
RedactedNzbTitle.rar
```

**Comment by hugbug** [comment]
The redacted log misses important details. Please post the original log or send it to me to nzbget@gmail.com.

**Comment by hugbug** [comment]
That's rar-renamer module misbehaving. What is your nzbget version?
Can you please send me the nzb-file?

**Comment by aerickson** [comment]
I've been running from the head of the develop branch. I recompiled last night (was ~20 commits behind). Here's what I'm on now. 

```
INFO    nzbget 20.0-testing-r2169 server-mode                                                                                     
```

Yes, will send the nzb via email.

Thanks.

**Comment by hugbug** [comment]
This must be fixed now. If the problem occurs again please reopen the issue.

**Comment by wusamba** [comment]
nzbget version: 21.0
- added nzb paused and with duplicate check disabled
- inside the nzbfile is a corrupt duplicate (normally recognized by duplicate check)
- nzbget starts downloading with directly unpacking
- collection was completely downloaded; Unrar: All OK; Direct unpack successful
- nzbget found archive files not processed by direct unpack, unpacking all files again
- Unrar: Extracting from filename.duplicate1.rar
- Unrar: WARNING: You need to start extraction from a previous volume to unpack
- Cancelling unpack due to errors -> unpack requested par-check with forced repair
- Repair not needed -> performing full par-check
- second unpack attempt skipped due to par-check not repaired anything
- Unpack failed.

**But then: All previously unpacked files without any error (Unrar: All Ok) were deleted.**

It is a rare scenario, but I wanted to mention it.

Thanks for your great work!
