### ISSUE TITLE
ARM64

### ISSUE THREAD

**Issue by woiza** [nzbget/nzbget#524]
I have two arm64 boards (Rock64 and NanoPi Neo Plus 2) and the 32bit version of Nzbget works fine on both of them. Are there any benefits to compiling and running a 64bit verision of Nzbget? What are the advantages and disadvantages of 32 and 64 bit ARM builds of Nzbget?
Using your offical stable or testing build on an arm64 board, is NEON / SIMD enabled by default? How can I check this?

**Comment by hugbug** [comment]
My attempt to create a 64 ARM bit build which would work on any system (statically linked) failed. Although the executable was compiled successfully, it showed some strange behaviour during tests: some system functions didn't work properly.

In general providing static builds which work on any system is tricky.

Nonetheless @sanderjo has build nzbget natively on NanoPi Neo in 64 bit mode and compared the speed to 32 bit version from official installer.  The speed was [similar](https://github.com/nzbget/nzbget/issues/418#issuecomment-318165115).

As far as I can remember I did speed tests with partially working 64 bit binary and the speed difference was not big, I can't remember which one was faster.

SIMD and CRC are automatically enabled if CPU supports them. There is no way to enabled/disable them manually. The **debug** version of nzbget (v20) [prints debug-messages](https://github.com/nzbget/nzbget/blob/develop/daemon/nntp/Decoder.cpp#L29) indicating if features are active. The speed achieved by debug build should not however be used for speed comparisons because debug builds have all other compiler optimisations disabled.

The best is to compare v19 (release build) to v20 (release build). Whether it uses SIMD or not is a secondary thing for end users; SIMD doesn't bring that much performance boost in nzbget on ARM but other optimisations in v20 do.

**Comment by woiza** [comment]
got it, thanks for the explanation.

**Comment by sanderjo** [comment]
> Are there any benefits to compiling and running a 64bit verision of Nzbget? 

For me: cool to compile & run 64-bit ARM software on such a tiny device. So: "because you can"

And maybe useful in pushing the envelope further, and make 64-bit ARM more mainstream. My hope is that that experience can help @hugbug to provide prebuilt 64-bit ARM in the future.

**Comment by woiza** [comment]
Same here, I really like arm64. I will try to compile nzbget for arm64 and also try to create a docker image on docker hub (with Qemu) once v20 is released.

**Comment by hugbug** [comment]
Please let me close this issue.
Currently I don't have TODOs in this regard.
