### ISSUE TITLE
NZBGET is broken via Docker

### ISSUE THREAD

**Issue by OutdoorTree90990** [nzbget/nzbget#556]
Hi, myself and other members received a nzbget push.  You cannot login with prior login and if you use the default, you will get an error page for the unstable version.  Just an FYI.

**Comment by zhdenny** [comment]
I see it here too. It only accepts the default login creds.....then just rolls right into an error page. Cannot access.

`Successfully installed into /app,
Web-interface is on http://localhost:6789 (login:nzbget, password:tegbzn6789),
For support please visit http://nzbget.net/forum,
[cont-init.d] 10-install-app: exited 0.,
[cont-init.d] 11-setup-config: executing... ,
[cont-init.d] 11-setup-config: exited 0.,
[cont-init.d] 20-mount-rclone: executing... ,
[cont-init.d] 20-mount-rclone: exited 0.,
[cont-init.d] 21-mount-rar2fs: executing... ,
[cont-init.d] 21-mount-rar2fs: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
/root/downloads/nzbget.log: Permission denied,
/root/downloads/nzbget.log: Permission denied,
/root/downloads/nzbget.log: Permission denied,
/root/downloads/nzbget.log: Permission denied,
/root/downloads/nzbget.log: Permission denied,
/root/downloads/nzbget.log: Permission denied,
nzbget.conf(0): Invalid value for option "TempDir" (/root/downloads/tmp): could not read information for directory /root/downloads/tmp: errno 13, ,
nzbget.conf(0): Invalid value for option "QueueDir" (/root/downloads/queue): could not read information for directory /root/downloads/queue: errno 13, ,
nzbget.conf(0): Invalid value for option "NzbDir" (/root/downloads/nzb): could not read information for directory /root/downloads/nzb: errno 13, ,
[ERROR] nzbget.conf(0): Invalid value for option "TempDir" (/root/downloads/tmp): could not read information for directory /root/downloads/tmp: errno 13, ,
[ERROR] nzbget.conf(0): Invalid value for option "QueueDir" (/root/downloads/queue): could not read information for directory /root/downloads/queue: errno 13, ,
[ERROR] nzbget.conf(0): Invalid value for option "NzbDir" (/root/downloads/nzb): could not read information for directory /root/downloads/nzb: errno 13, ,
[INFO] Pausing all activities due to errors in configuration,
[ERROR] Could not read configuration templates,
[INFO] nzbget 20.0 server-mode,
/root/downloads/nzbget.log: Permission denied,
[WARNING] Web-Server: 503 Service Unavailable, Resource: /,
/root/downloads/nzbget.log: Permission denied,
[WARNING] Web-Server: 503 Service Unavailable, Resource: /favicon.ico,
/root/downloads/nzbget.log: Permission denied,
/root/downloads/nzbget.log: Permission denied,
[WARNING] Web-Server: 503 Service Unavailable, Resource: /,
[WARNING] Web-Server: 503 Service Unavailable, Resource: /favicon.ico,
/root/downloads/nzbget.log: Permission denied,
/root/downloads/nzbget.log: Permission denied,`

**Comment by hugbug** [comment]
NZBGet project doesn't provide any docker images. You use docker image created by other developer(s). Please let him (them) know there is an issue with the image.

**Comment by mrhotio** [comment]
This issue is not related to the project NZBGet, please feel free to close this issue.
Sorry for the inconvenience @hugbug 

For those affected: check the file size of nzbget.conf, notice the 0KB and that it is empty.
