### ISSUE TITLE
Cannot use root drive for category path

### ISSUE THREAD

**Issue by beefycheddar** [nzbget/nzbget#566]
I think this may be similar to issue #247 

I can't set an explicit path for categories. I have a separate drive where I want TV shows to be placed while awaiting sonarr import. When I configure that path, s:\dl\c\tv, nzbget still post-processes them into the $destdir path, m:\dl\c, and subfolder, \tv, for a full path of m:\dl\c\tv. This behavior is reflected in both application mode and service mode. The config file does show the correct path. 

I don't see an "invalid value" in the log file.

What else can I look for?

Thank you

**Comment by hugbug** [comment]
If you add new nzb using webui (not via sonarr) and choose correct category when adding file - does it download into correct directory?

**Comment by beefycheddar** [comment]
Excellent question. Thank you for that. 

If I add the show manually, it does end up in the correct output directory.

Is there a setting for that somewhere in Sonarr? I haven't found one, yet.

**Comment by hugbug** [comment]
Do items added via Sonarr have correct category in nzbget? Click on an item in queue or history and check category. Is category name correctly written? If Sonarr would pass a misspelled category name nzbget would accept it and show but destination directory will not be set since category name will not match to the one in settings.

**Comment by hugbug** [comment]
Closing this due to lack of feedback.
Feel free to post further comments and I may reopen the issue if necessary.
