### ISSUE TITLE
Use multiple threads during extraction

### ISSUE THREAD

**Issue by greencopper** [nzbget/nzbget#583]
Hi,

Is it not possible to somehow have unrar use multiple threads during extraction?

Kind regards

**Comment by hugbug** [comment]
Generally this should not be necessary because usually files posted to Usenet use rar only as container for file splitting without compression.

Nonetheless if you need this and you have unrar which supports multithreading and this feature in your unrar isn't enabled by default and requires special switches you can adjust command line parameters passed to unrar by NZBGet via option **UnrarCmd**.

Also NZBGet can process (unpack) multiple downloads simultaneously when enabled via option **PostStrategy**.
