### ISSUE TITLE
NZBGet Loading no reponse

### ISSUE THREAD

**Issue by Viper911** [nzbget/nzbget#589]
Seems to only happen when I have a lot of files queued up for download, otherwise works fine.  After running most of the day with 400+ things in queue it will randomly stop working (siting at loading screen).  I try and restart the windows service and window reports it unable to stop it.  Only a server reboot seems to work.  I've even gone so far as setting up a windows job to reboot the server nightly to try and keep it up, but still have long gaps of downtime with this solution if it locks up a few hours after reboot.

Nothing the logs..

Thoughts?

**Comment by hugbug** [comment]
When it stops working - is the process still running?

If the service can't be stopped (and the process is still there) it seems to hang. Try terminating the process from Task Manager. At least that saves you the reboot.

What version of nzbget you are running? Try the latest testing.

**Comment by Viper911** [comment]
Yes it still shows as running and can’t be stopped.  I an running stable 20.0.  What’s new in the testing you think would solve this issue?


________________________________

**Comment by hugbug** [comment]
> What’s new in the testing you think would solve this issue?

If you use RSS feeds there were many changes. Otherwise - probably nothing.

Please try this:
- enable crash dumps as explained in [Crash dump](https://nzbget.net/crash-dump);
- install the [latest testing debug version](
http://nzbget.net/download/nzbget-latest-testing-bin-windows-debug-setup.exe);
- if it crashes the crash dump should be created automatically (see the article linked above);
- if it hangs - open Task Manager, right click on process and choose "Create Dump File".

Send the dump and the log-file to me via Google Drive or similar service (compress it first). With the dump there is a hope I'll be able to determine what the process is doing.

**Note:** the memory dump contains the whole memory of the process including all program options including all logins (newsserver etc.). You can erase them using some hex editor which can replace in binary files, make sure to replace with a string of the same length.

**Comment by hugbug** [comment]
Closing this for now. Feel free to reopen or add posts with updated info.
