### ISSUE TITLE
Remove suggestion about RC4 cipher

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#611]
Settings page of web-interface suggests `RC4-MD5` as fastest cipher. This is not true for modern CPUs with hardware support for AES.

The settings page should be updated to reflect that. The same applies to article [Choosing Cipher](https://nzbget.net/choosing-cipher).

**Comment by animetosho** [comment]
Hi, I thought I'd bring this up as there was [some discussion around this topic](https://old.reddit.com/r/usenet/comments/bk5zhl/nzbget_v21_released/eme85z6/).

I note that [the page](https://nzbget.net/choosing-cipher#update-2019) now mentions `AES128-SHA` or `AES256-SHA` (though you actually tested `AES128` in [your benchmark here](https://github.com/nzbget/nzbget/issues/448#issuecomment-340221832) and found that to be fastest).

My general recommendation would be:

* `AES128` for most users
* `CHACHA20:RC4-MD5` if running an old CPU without AES acceleration. This may not work (CHACHA20 has low adoption and not available in OpenSSL 1.0.1, and RC4-MD5 is removed in OpenSSL 1.0.2 (?) or later), so if it doesn't, `AES128+SHA` (note the `+` instead of `-`) is probably the best bet
* I don't know about GnuTLS, but OpenSSL is generally faster from experience (may no longer be true, I've done no testing with GnuTLS in the last few years). *If* my presumption holds true, performance conscious users may wish to use OpenSSL instead
