### ISSUE TITLE
Lost NZBGet queue, can I re-scan queue folder?

### ISSUE THREAD

**Issue by victorshx** [nzbget/nzbget#624]
I reloaded NZBget and I lost an entire queue of 550+ downloads, but I have FlushQueue enabled.

May I know how do I proceed to scan the queue from the respective path to resume downloads?

**Comment by hugbug** [comment]
The queue is saved in file "queue" in QueueDir. If that file is damaged the queue can't be loaded.

What do you mean with lost? Hardware issue with disk holding QueueDir, something else? With FlushQueue enabled the queue should be in good shape even if program crashes. Hardware failures or PC freezes may still lead to lost of data.

The queued nzb-files are stored in NzbDir (with extensions ".queue"). You can rename them (if you know which ones) by removing ".queued" and then using button "Scan incoming directory" in "Add-dialog" in web-interface.

**Comment by victorshx** [comment]
I do know where is the QueueDir, but I would like to know how to force NZBget to load the queue from the directory as the download queue is gone after I did a soft reload.

I also know where is the NzbDir(.queue), however, I couldn't bulk import the nzb files. The main reason is that I use Sonarr/Radarr to automate downloads of movies and TV series using Usenet and upload onto Google Drive. If I were to bulk import everything, does it mean I have to re-download everything when I have it on Google Drive?

**Comment by hugbug** [comment]
> I would like to know how to force NZBget to load the queue from the directory 

The problem is it can't load something that doesn't exist. If the file queue is gone/corrupted then the queue data is lost. The remaining files contain information about article ids but that is not enough to rebuild queue.

Send me the content of QueueDir to nzbget@gmail.com and I'll check if something can be done.

> If I were to bulk import everything

You should try to find out which files you already have downloaded. Timestamps of .queued-files could be useful.

>  the download queue is gone after I did a soft reload

That sounds like a serious bug that needs to be investigated. Can you please send me the log-file (or all of them if log rotation is active)?
