### ISSUE TITLE
par failure logic on manual cleanups and duplicates

### ISSUE THREAD

**Issue by nomandera** [nzbget/nzbget#64]
Under 15.0 stable.

To recreate:
- a download fails for any reason
- add a second nzb using the allow duplicate option e.g nzb named the same but rars within nzb differently named/obfuscated
- the new download folder name matches and the contents of the rars match but the rars themselves have different name

This second download will always fail (even though the new par2 will pass when manually checked). I can only assume it is failing because the contents of the first failed nzb are in the same folder and influences this in some way.

Also if you now manually par2 verify, unpack and clean-up using the shell and then tell nzbget to post process again (i.e. in order to run all the other post processing scripts) this will also fail at par2 verification (even though there are no longer any par2 and the unpack etc is done).

**Comment by nomandera** [comment]
Perhaps this is actually a veiled feature request. The usage scenario is when multiple different releases of the same content exist but some or all of them are incomplete and broken. In most cases by downloading all the files from each pack and running "par2repair -N XXX.par2 *" you end up with one or more being fixed.

**Comment by hugbug** [comment]
Is option InterDir active (not empty)?

**Comment by nomandera** [comment]
Option is empty.

> InterDir=

**Comment by hugbug** [comment]
That's why this is happening. By default it is not empty. You must have set it yourself empty.
When InterDir is active every download has a unique download directory and par-processing directory and such problems not happen.

**Comment by hugbug** [comment]
### A small explanation

When a par-check is performed all par2-files in the destination directory are processed. There is no tracking what files were downloaded. The files are processed regardless of how they landed in the directory. That makes the processing transparent and predictable. If necessary you can manually put extra files (par2-files or rar-files) into download directory and retry processing.

**When option InterDir is active**
Every download become an unique directory inside InterDir, where all files are downloaded and par-checked. The unpack is performed directly to destination directory (DestDir).

**When option InterDir is empty**
Files are downloaded into final destination directory. Downloads having the same name will be downloaded into the same directory and will be processed there. If during processing there are any other files in the directory they are processed as if they were downloaded because there is no differentiation. That may lead to unpredictable results. Therefore the using of option InterDir is recommended.

**Comment by nomandera** [comment]
I have no recollection of setting the intermediate directory as empty but it is entirely possible (maybe even likely) that I did some time in the long past. Certainly it explains all the symptoms I am seeing and I will experiment with this setting (big thanks for the clarification).

It does open the question on the use case where you manually add (force) the addition of a duplicate nzb when the existing one is marked as failed. In this scenario should the duplicate fail you ideally want to check if the original can contribute parity blocks or vice versa. Obviously this constitutes quite a bit of parity related disk thrashing so it needs some thought as to if it could be cleanly implemented (especially for triplicate nzbs etc). If successful though it would add a extra level of download success and clean up the history where nzbs are repaired but marked as failed.

**Comment by hugbug** [comment]
Nzbs with the same name not necessary have identical content. Trying to automate the described use case is too error prone. Let's leave such cases for manual processing.

Actually in your case the two downloads (with same name) had **different** content. Otherwise the par-check would success. And since there are two different archive and par2 sets there is no way for NZBGet to know if they both have the same title. It's logical to fail if one set isn't repairable.

**Comment by nomandera** [comment]
The content in this example is only different in so far as the rars sets (which arent compressed) are named differently. The contents of the rars are identical and the only place they are different on a parity block level are where the rar files split.

But you are right the contents could be different just because the nzb names are the same doesn't guarantee the contents are the same (although arguably more time than not they will be).

What I can say is that in the real world I have a high success rate (~70%+) repairing broken rar sets of this nature by downloading all the files for all versions of it (often 2-4 nzbs) and then systematically trying each parity set.

I agree this is probably too "vague" to be automatic but there could be a way to manually tell nzbget to "merge, download all and then try each par set in turn".

I may not be explaining myself very well but I am confident in validity of this approach as I have just achieved a fix by doing just this with 3 different nzbs sets all of which on their own fail under nzbget.

Food for thought

**Comment by hugbug** [comment]
> I have just achieved a fix by doing just this with 3 different nzbs sets all of which on their own fail under nzbget.

There is no way to use one par-set with other rar-set. Although the movie-file inside these two rar-sets may be the same, since the rar-sets were created with different part-sizes the rar-sets are not identical. The belonging par-sets are not identical too and are not interchangeable. Putting all rar-sets and par-sets into one directory doesn't help. There are two possible explanations why it works sometimes:
1. the rar-sets/par-sets were indeed identical (a repost). That's a rare case.
2. one of those nzbs was OK (repairable) on its own. If you have downloaded both nzbs in one directory in nzbget, it cannot repair the both sets and the entire download was marked as failed. If you used InterDir then one of these downloads would succeed.

**Comment by nomandera** [comment]
rar sets of videos are in reality usually just split files with a rar header per split. Because of this if you tell par2 to scan all files it will blindy look for blocks withing these split files. At all split points the blocks fail because of the rar header and the split but often other blocks are found.

This not rare I do it all the time with wildly differently named rar sets with different rar file sizes.

I am 100% certain each nzb on their own in these cases fail and when everything is brought together into one directory blocks are found from the other rar sets. I am certain of this because par2 feeds back when it find blocks from the other sets.

I admit it does not work always but "There is no way to use one par-set with other rar-set." is simply not correct. I do it manually all the time (for years) even when one source is not usenet.

Note: What you say was true with par1 but not with par2 :)

**Comment by hugbug** [comment]
**Hell you are right about not compressed rars :scream:**

So what would be a workflow to process such cases properly in NZBGet and still not spoil the other cases where multiple rar/par-sets must all be processed correctly for success (current behavior)?

What is possible already is to merge multiple nzbs into one download - via button **Merge**.

Now we need a way to tell NZBGet: hey, try process all par-sets and all rar-sets - if one succeed - that's the only thing I need. Mark it as success then.

**Comment by nomandera** [comment]
**Merge** seems the like natural place for this since it is always instigated manually by a human. It also fits nicely into the workflow by keeping the history neatly representing the new reality of "merge and fixed" and "merge and failed". Currently I have to do this part manually since i dont like the history showing stuff I know i fixed as failed.

I wonder if there is a use case where users merge nzbs but dont want each parity set tested in turn. If there is not or it is rare then I think we have the place where it should go.

**Comment by hugbug** [comment]
Do you mean we need **Merge** for history items? So you have multiple nzbs tried separately and then you tell NZBGet to merge them and try together?

I have another idea, a whole lot harder to implement but fits better into duplicate handling workflow.

### Current workflow

Add multiple nzbs for the same title, NZBGet identifies duplicates and downloads one by one until success. The weak part here is duplicate identification, which works best together with RSS but not so good when adding nzbs manually.

### Improvement

If nzb fails during par-check the program activates AI (boom! :boom:) and automatically uses fragments from previously downloaded (and failed) nzbs.

### Challenges
- If nzb is deleted during download by health check, all downloaded files are typically deleted from disk. This is controlled by option DeleteCleanupDisk. The files are not deleted if nzb failed during post-process though;
- it should identify the same rar-content to not try nzbs with different rar-content. The content can be identifying via rar-header (movie file name and size);
- there are sure other problems, I have to think more about this.

**Comment by nomandera** [comment]
The more I think about it the more this is all about better duplicate handling.

Currently by default a user must always manually force nzbget to accept a duplicate named nzb.

However with better internal logic we can differentiate between two scenarios:
1. at least one previous match has passed
2. all previous matches have failed

Scenario 1 needs no change to the current setup and should continue to allow manual allowing "ignore duplicates".

Scenario 2 is potentially also simple where we create a new "default on" config option that ignores duplicate matching for this specific scenario. This means that a user or tool can upload duplicate nzbs and not have to do any extra work to allow these legitimate duplicates. Importantly true duplicate handling still works.

We also now have a clear trigger when the new "test all files against all par2" should kick in.

**Challenges**
- In scenario 2 we dont want to delete any files at all. Even sample files may contribute that elusive missing parity block. Not ideal since there are many post processing tools that may have kicked in to delete files.
- We now want to potentially repair sample files before we try the the new  "test all files against all par2" 
- How do we handle someone adding lots of identically named nzbs at one go. All discussions so far have relied on each download having completed before we introduce the next.

**Comment by hugbug** [comment]
> Currently by default a user must always manually force nzbget to accept a duplicate named nzb.

No. The duplicate handling already works the way you want. Don't disable duplicate check when adding nzbs and they will be processed:
- if there is an item with SUCCESS status in history - the new item goes straight to history with status DUPE. You don't want to download the same title again, right?;
- if there are no items with SUCCESS status (all with FAILURE status or no items at all) - the new item is added to queue and downloaded;
- if there are items in queue already - the new item is added to history with DUPE status (and is used if necessary - see below).
- if you add multiple items at once - the first is added to queue, all others - to history with DUPE status.

Now, when download completes, if the item fails and there are DUPE in history they are downloaded one by one until success or until all fail.

The option "Disable duplicate check" is useful in rare cases:
- you add exactly same nzb - in this case you tell the program - "I know I have downloaded it before but I want download it again". A better alternative - find the item in queue and choose "Download again".
- you have different nzbs with different titles (totally different movies) but all having the same nzb-name. A much better alternative - rename nzbs before adding.

---

To not delete files from failed downloads set option HealthCheck=none. It also disables preliminary abortion of download; that's good because we want every piece.

**Summary:** It looks like the "only" thing needed to be improved is: the par-check should use files from other duplicates.

**Comment by nomandera** [comment]
I dont think I have any more value I can add here as you clearly, (and for obvious reasons), have a focused idea how this could be done now.

I can however test and act as a sounding board should you need it.

Kudos

**Comment by hugbug** [comment]
I'm experimenting with it. Can you please send me example nzbs for testing? (nzbget@gmail.com).

When I have a version to test, do you compile yourself or should I send you a compiled binary (which OS)?

**Comment by nomandera** [comment]
Just let me know what to checkout and I can roll my own.

I could send you nzbs but it will be hit and miss dependent on usenet providers availability etc.

I would start with just artificially damaging a couple of downloads first by removing enough rars that they both fail and then once confidence is higher corrupt random blocks directly. This way we can reproduce the test identically over and over.

After we get this working assuming there is a distinct log we can let nzbget tell us some real world examples that worked and didnt and use that for more detailed testing.

Make sense?

**Comment by hugbug** [comment]
Artificially damaged nzbs is what I'm testing with. Just wanted to do a couple of real life tests. They usually highlight new issues.

I'm using one nzb, from which I made a copy, then damaged both nzbs in different ways (removed different rars). When adding nzbs to queue they are detected as duplicates (they both have the same name) but are not detected as the same file (since the are not equal due to different parts missing). That simulates the issue.

However I would prefer to have two or three nzbs from the same video file where the archives were built with different part-size. Preferably a small download (500 MB) like an SD episode. The files shouldn't be taken down, I'l damage them myself for testing. I've tried to find something but it were always the same set of rar-files. If you have something like this that would be helpful.

**Comment by nomandera** [comment]
OK will get on it

Done. Check your inbox.

**Comment by hugbug** [comment]
I have something for you to play with.
- compile from git repository (see [Build the latest development version](https://github.com/nzbget/nzbget/wiki/Build-the-latest-development-version)) using branch **64-dupe-repair**;
- set options **ParScan=dupe**, **HealthCheck=none**;
- add two nzbs (modified so that each separately fails) as duplicates either using the same nzb-name;
- one nzb will appear in queue and another in history as dupe;
- when the first download completes it fails and the dupe will be moved back to download queue;
- the second should be repaired. Check the logs for that item (via history details -> Log). You'll see how it scans the rar-files from the first download.

**Comment by nomandera** [comment]
NZBGet 16.0-testing-r1378M (64-dupe-repair)
ParScan=dupe
HealthCheck=none

I tried this with a real pair of nzbs I have seen fail in the past by uploading the first nzb (ticking ignore dupes) and then the second  (NOT ticking ignore dupes).

In history I can see one nzb being marked as copy and another as failure after the download compelted. However I do not see any logs suggesting anything special has happened beyond that. My incomplete directory only contains one folder related to the failed nzb and my complete directory none.

Also I can see on the failed nzb that my post processing scripts have run messing with the data i.e. deleted samples etc 

I do not know what "(via history details -> Log)" means I have been using "messages" and the raw logs.

I think I have replicated what you have asked for. What can I do now to test further?

Edit: let me do exactly what you asked for using artificially broken nzbs first
Edit2: OK the exmaple I chose above was a complete mess with sample file par2 named as the real video. A terrible trial case so ignore.

**Comment by hugbug** [comment]
Don't tick "disable duplcate check". Doing so marks an item as unique and it doesn't participate in any duplicate related workflows.

To see log click on a history item you want to inspect, then on button "Log", you'll see the full download and processing log of this item. No need to go through the big general log-file or messages tab. Option NzbLog must be active.

Current implementation does not inspect content of directories or archives and scan all files in dupe directories. You should have the same or similar repairability quota as if you would put all files in one folder and try manual repair.

**Comment by nomandera** [comment]
> Don't tick "disable duplcate check". Doing so marks an item as unique and it doesn't participate in any duplicate related workflows.

That explains my mistake. On a side note I always interpreted "disable duplcate check" as "allow me to upload a duplicate". When interpreted in this way "doesn't participate in any duplicate related workflows." is potentially confusing.

> To see log click on a history item you want to inspect, then on button "Log"

Somewhat embarrassed I have never noticed this before. Works perfectly.

Will retest ASAP.

**Comment by nomandera** [comment]
Whilst I was waiting to test with two broken nzbs a real life example came on.

NZB one failed. Manually added NZB two which was immediately queued. After some repair NZB two repaired itself.

However NZB one incomplete files remain. Since NZB one wasnt actually used in this process that makes sense however ideally we wouldnt be left with any intermediate files.

**Comment by hugbug** [comment]
> NZB one failed. Manually added NZB two which was immediately queued. After some repair NZB two repaired itself.

If the download was repaired on it's own that's not our test case ;)

> however ideally we wouldnt be left with any intermediate files.

The files will be deleted in two cases:
- automatically, after the history hold time expires (option **KeepHistory**), by default 30 days;
- manually, if you mark the successful item using command **Mark as good** in history.

The failed files are not deleted automatically immediately because, well, may be you'll find extra pars or redownload pieces from another provider.

In a special case when failed duplicates contain exactly same content (same video file) as a successfully downloaded or repaired another item, in that case it indeed makes sense to delete files from failed duplicates. That's not a priority feature at the moment however. It requires a very good "same content"-check to avoid false deletions.

**Comment by hugbug** [comment]
**Update:** option HealthCheck can be now set to "Delete". A special handling (when ParScan=dupe) prevents deleting of valuable but corrupted downloads. Only if the download has less than 10% of success it is deleted. 

This adjustment allows to use health check (=delete) to quickly abort DMCA'ed downloads (100% missing) but still keep partially damaged downloads which are not repairable on they own.

**Comment by nomandera** [comment]
Tested pre the HealthCheck update successfully. It "just worked" but I found it odd remnants of the initial nzb donwload remained after the repair.

Will test again in the AM with the new HealthCheck options.

Excellent work.

**Comment by nomandera** [comment]
NZBGet 16.0-testing-r1379M (64-dupe-repair)
HealthCheck=Delete

Tested POST the HealthCheck update successfully. So far I cant break it and it successfully fixes stuff I would have had to do manually before.

Two thoughts:
1. A clear log entry for when this new technique is successful with any other relevant data would be useful. As it stands it is quite easy to miss even when you look for it.
2. Some way to differentiate between "traditional failed downloads" and the "new failed downloads" that have subsequently been used to create a successful download (so that you can clean up manually if you prefer not to wait to delete).

**Comment by nomandera** [comment]
A clearer use case for thought number 2.

When applying a filter for failed downloads on the history tab you should be able to differentiate, or perhaps not even see, entries that have subsequently aided in creating a fixed download.

**Comment by hugbug** [comment]
That's a general issue with duplicates. There can be multiple items in history, all referring to the same title, possibly in different qualities, all with different statuses. Not showing items just because there is a success item isn't right. Showing them with a different status doesn't feel right too.

I would somehow visually highlight failed (etc.) items having success duplicates. A problem here is that such detection can be CPU heavy since a reiteration through history  must be made for every history item; all of that for every page refresh. Alternatively such status could be calculated once and then stored in the item, which brings a bunch of other problems to solve in order to keep the status up to date.

**Comment by hugbug** [comment]
### Improvement

Before scanning of dupe directories the directories are quickly checked by dupe matcher. It determines if they contain or may contain the same content. If the dupe checker detects a dupe containing different content as the download being currently processed by par-checker, such extra dupe is skipped to save time during dupe par scan.

When comparing the directories the contents of rar-archives are scanned and compared. The dupe matcher uses pessimistic strategy and aborts scan only if it is sure that the contents are different. In most cases it can accurately detect different downloads.

**Example:** two downloads for the same title (with same dupekeys or nzb name). One download is for 720p and another for 1080p. The dupe matcher detects that the files have different sizes and will not scan files from other download.

**Comment by hugbug** [comment]
Merged into **develop** branch. Please use develop for further testing.

I'll think something out about how to present the info when dupe scan was used.

**Comment by nomandera** [comment]
Dupe checker sounds like a good improvement.

I have moved to NZBGet 16.0-testing-r1383M and can test anything you need if/when needed.

I have used this new feature to fix over10 real nzbs. Caveat I guess I have as it is very hard/impossible to tell for the logs if we used any data from the original broken nzb download to contribute or if the second just worked on its own.

**Comment by hugbug** [comment]
Some kind of indication in web UI is in my TODO-list.

Nonetheless:

Message **Found extra <N> blocks in dupe sources** indicates that another nzbs were used to repair this one.
Therefore the easiest way to find out nzbs which were repaired using the new mode is to search for **dupe sources** in the global log-file.

A better thing: I could write a pp-script which will send you an email alert every time the new repair mode was successfully used.

**Comment by hugbug** [comment]
Here it is: [PP-Script Log-Alert - send email on certain log messages](http://forum.nzbget.net/viewtopic.php?f=8&t=2084).

**Comment by nomandera** [comment]
very useful pp-script in general thank you

**Comment by hugbug** [comment]
### Update

added indication of par-repair using dupe sources in history details dialog:
- status “REPAIR: RECIPIENT” or “REPAIR:DONOR” with hint details;
- in statistics details (via click on “Total downloaded ->”).

Note: new status field "REPAIR" will be shown only for items, added to history with the updated code.

There is still no way to quickly filter history items on this criteria. But I'm working on #72 (Advanced search capabilities). Once done it will be possible to filter related history items by typing in the search box: **(repair-status:recipient | repair-status:donor)**.

**Comment by hugbug** [comment]
### Update
- renamed status “REPAIR" to "EXPAR";
- new field **ExParStatus** returned by API-method "history" with possible values NONE, RECIPIENT, DONOR.

With the advanced search implemented in #72 the relevant items can be filtered by typing in the search box on history page:
`-exparstatus:none`
This means: show all items whose ExParStatus isn't "NONE". The same can be achieved with a longer search text:
`exparstatus:recipient | exparstatus:donor`

**Comment by hugbug** [comment]
I consider this feature done.
If there are any troubles feel free to reopen the issue.

**Comment by nomandera** [comment]
I have been thinking about this since its introduction. Writing here, will fork if required.

There are two more use cases that fall within the umbrella of this new feature.
1. Currently tools that watch for releases and then feed the nzb to nzbget have no option to pass one nzb at a time. Some of these tools will try with varying success to monitor completion and pass a second nzb on failure. This is complex and the reason most tools dont implement this logic. Perhaps we should now encourage the sending a pack of nzbs in the first instance placing the responsibility of retrying failures etc on us (which we now do anyway). This idea is not fleshed out. Will give it more attention if it is interesting.
2. Often whilst multiple releases will all have the primary content some will not have the auxiliary content e.g all have an mkv but some miss files like nfo, sub etc. Ideally we would automatically cater for this although i realise it relies on teaching nzbget what constitutes a release pack which may not be ideal or too complex to be reliable.

**Comment by hugbug** [comment]
Do you have any statistics for the duplicate repair feature? The filter `(repair-status:recipient | repair-status:donor)` on history should show the related items.

**Comment by nomandera** [comment]
Sorry I was afk with real life stuff.

This search in history is blank. Admittedly I have been having a good run recently and I have only upgraded beyond v16 stable today but I find it hard to believe I have not one single result.

Especially since we forced some during testing.

**Comment by hugbug** [comment]
1. Only history entries created after implementing of new status field "exparstatus" (after 17 August) can be found with the search.
2. The search looks only in _visible_ history records. _Hidden_ records do not keep the exparstatus information. Check option **KeepHistory**, which sets when the records are transformed into hidden entries.

Nonetheless the question remains whether the feature brings real benefits.

**Comment by nomandera** [comment]
That makes sense. I will keep up to date and monitor then report back some stats before we take this any further.

I will say thought that even small numbers for me are high value.
