### ISSUE TITLE
Firefox on page load/start "unable to connect"

### ISSUE THREAD

**Issue by despecial** [nzbget/nzbget#643]
when starting NZBget the browser tab often has to be reloaded to show the webinterface.
not sure if it is not ready when the tab opens or whats causing the page not to show up, only after a quick refresh/reload.

**Comment by hugbug** [comment]
I'm using Firefox and haven't experienced that issue.
Can you please provide more information:
- is this first time you use nzbget? If you are a long time nzbget user - since when the issue started to happen? Was that an update of nzbget or an update of Firefox?
- what OS nzbget runs on?
- what OS Firefox runs on?
- are nzbget and Firefox on the same computer?
- is nzbget accessed via a reverse proxy perhaps (nginx or apache)?

**Comment by despecial** [comment]
- long time user, if I remember right, it began with beta 20.* (so a couple of months ago)
- Mojave, 10.14.5
- FF 67.0.1
- Yes, both on the same machine
- no proxy, just a normal installation, no extras configured

**Comment by hugbug** [comment]
If this issue is still relevant - please test with the latest testing version r2329 and report back. I'll reopen issue if necessary.
