### ISSUE TITLE
unar/lsar support

### ISSUE THREAD

**Issue by caronc** [nzbget/nzbget#649]
**unar** and **lsar** are 2 completely open source tools that don't have any strange licensing issues. Combined they can replace the **unrar** tool. This change is the only way I'm going to be able to _properly_ get NZBGet onto EPEL/Fedora since unrar's licensing is the only thing holding your app back from being 100% open source.

* *unar*: extracts rar files and supports v5 passwords
* *lsrar*: lists the contents of the rar and can also test it's integrity.
    * This plays more of a role in the _daemon/postprocess/DupeMatcher.cpp_

You can read more about the package [here](https://theunarchiver.com/command-line).

The way i was thinking that the way it could be implemented:
1. ALWAYS use **unrar** *if defined* and the *binary exists*
2. Alternatively use **unar** as a backup (if defined) and unrar was not found

I started a branch already addressing this and i think I'm about 80% of the way there.  The only problem I'm having is working with the drastic differences in output from **lsar** in comparison to **unrar lt**.

I was hoping for both your feedback/comments and review of what I've done. My knowledge in C++ isn't as good as yours, so go easy on me :wink:.

1. [Here are the changes I have so far](https://github.com/nzbget/nzbget/compare/develop...caronc:unar-support)

**Comment by hugbug** [comment]
From the info I was able to gather about The Unarchiver it seems it was free once but has been acquired by some company. I haven't found a source code project (with source code, history, issue tracker), only a zip-download from the unarchiver web-site. That doesn't look like a community oriented project to me.

It also seems unlikely to me that someone has developed a full rar-compatible software without looking at unrar sources and if they did then their license must have the same restrictions as unrar license.

Can't you just package nzbget without unrar and let users install proper unrar on their own?

**Comment by caronc** [comment]
> From the info I was able to gather about The Unarchiver it seems it was free once but has been acquired by some company.

Do you have a source for this info. As far as i can tell this is not the case.

> I haven't found a source code project (with source code, history, issue tracker), only a zip-download from the unarchiver web-site. That doesn't look like a community oriented project to me.

Unrar (via RarLabs) doesn't have an issue tracker and history either.  They only provides a zip file containing their source from _[their download page too](https://www.rarlab.com/rar_add.htm)_, but that doesn't discourage you from using it :wink:.  Unar is  identified to be LGPLv2+ and thus is completely 100% open source regardless of how the maintainer chooses to share the product.

> It also seems unlikely to me that someone has developed a full rar-compatible software without looking at unrar sources and if they did then their license must have the same restrictions as unrar license.

I'm not sure if it's ideal to just assume this.  It already ships today with [Debian](https://packages.debian.org/stretch/unar), [Ubuntu](https://launchpad.net/ubuntu/+source/unar/), [Fedora, Red Hat](https://src.fedoraproject.org/rpms/unar), [Arch Linux](https://www.archlinux.org/packages/community/x86_64/unarchiver/), [Linux Mint](https://community.linuxmint.com/software/view/unar), etc, etc. As part of a distribution means it's subject to it's own bug reports and tracking systems. Effectively unrar fits in _some_ distributions, where as unar fits in them all.

> Can't you just package nzbget without unrar and let users install proper unrar on their own?

Today that's the way it is; it's on [nuxref](http://nuxref.com/nuxref-repository/); an external repository to which I host and ignore free to use software licenses that violate the Free Software Foundation (FSF) standards (similar to distributions like Ubuntu does).  Fedora has this too; but it has to be done through external (ever-changing) eco-systems that doesn't merit the same feat as having it part of their own distribution.

I guess my goal was to be able to put your product straight into Fedora/Red Hat packaging without any Licensing issues at all. You'd literally 'just work straight out of the box'.  NZBGet is already 99% of the way there because all of your other project dependences all follow the recognized open source standards.  **[Only unrar inhibits you from completing this task](https://fedoraproject.org/wiki/Licensing:Unrar)**

--
I'm **not** suggesting to drop the *unrar* support or get rid of it in any way, shape, or form. I'm just looking to add *unar/lsar* support as a backup and/or a secondary supported method.

Perhaps the lack of popularity of unar is holding you back? Personally,  I only learned of it a few days ago myself. But the product is mature; its been around for years. While unRar can probably handle some real crazy edge cases unar can't (_assumption here - who knows_), unar still seems to truck along just fine with all of the same core features and support.

Thoughts?

**Comment by hugbug** [comment]
> Do you have a source for this info.

[MacPaw acquires the Unarchiver.](https://macpaw.com/press/macpaw_acquires_unarchiver_the_robust_file-extraction_utility?clickid=TTWws6y4DzwZRZbRIW2nZ1XeUklRmQwneQth3U0&iradid=66209&irpid=10078&utm_content=ONLINE_TRACKING_LINK&utm_campaign=Skimbit%20Ltd.&sharedid=&utm_medium=affiliate&mpaid=3&utm_source=impactradius)

The announcements is from 2017. The source code and the precompiled binaries provided on their site  are dated May 2016. So no development in past three years. The source code was previously hosted on [google code](https://code.google.com/archive/p/theunarchiver/) but it's no longer maintained (the commit history ends in Aug 2015).

Don't you see a relation between acquiring of the product and the elimination of community web-site with source code, history and issue tracker? And the lack of development since May 2016?

> You'd literally 'just work straight out of the box'.

I've tried unar quickly, using precompiled binaries for Mac from their site, and that's what I see:
- no progress indication during unpack;
- direct unpack not possible due to a lack of "insert next disk"-mode.

What can we do about this? Exactly nothing because guess what - there is no issue tracker or forum to report the issues. They are clearly not interested in community feedback.

In current form unar is not a proper replacement of unrar for NZBGet.

**Comment by caronc** [comment]
> ... there is no issue tracker or forum to report the issues. They are clearly not interested in community feedback.

They certainly don't have the the maturity unrar has, but their support works the same way as Rarlab's does.  You still raise a good point thought; unar is just following in the same footsteps.  I sent MacPaw an email through their support system asking about this exact thing.  An immediate auto-response claims their turn-around human response time is within 24 hrs;  we're getting close to 18hr now and no reply yet. I did this shortly after your last reply; i'll keep you posted if note-worthy.

> In current form unar is not a proper replacement of unrar for NZBGet.

I just want to be clear; again, I'm not looking to replace unrar.  I'm looking to provide a secondary/backup alternative. unrar should always take precedence over unar if both are present. Is it acceptable to just deny those who chose `DirectUnpack` and lack unrar? It's just an option in the `nzbget.conf` file at the end of the day anyway.

Thoughts?

**Comment by hugbug** [comment]
I don't want users to use unar because such users will have inferior experience in NZBGet. I'd rather ask them to do manual steps with installing unrar instead. Well, in fact I don't have to ask them to do that; they just need to install nzbget via installer from nzbget home page.

Why do you compare web presence and support of unar to unrar? Unrar is a commercial product whereas unar (as you think) is open source. So compare it to other open source programs. I expect an  open source program to have some kind of web presence and community around it. I want my bug report or question to be seen by other users instead of hiding it like most commercial products do (they don't want the problems to be widely known).

I'm not against unrar alternatives but such alternative must be good enough. Currently that's not the case with unar.

If for your package you need a total independence from unrar you can just disable unpack as default setting. Every user who wants to use nzbget properly will need to install unrar and activate option Unpack.

If you can persuade unar owners to implement at least a proper progress indicator, we can think about supporting it in nzbget. We would need to make tests on a relevant set of Usenet rar-files first though. Again, if it has issues with some rar-files (I don't know that yet) I'd rather ask each user to install unrar instead of dealing with support requests about nzbget failing to extract some files.

**Comment by caronc** [comment]
> I'm not against unrar alternatives but such alternative must be good enough. Currently that's not the case with unar

Fair enough, I won't press this matter any further.
