### ISSUE TITLE
Can't get over 1000 Mbs speed.

### ISSUE THREAD

**Issue by steffanjensen** [nzbget/nzbget#652]
Hi i have a connection faster than 1000mbs speed, but when i use nzbget i only get around 800-900 mbs speed limit. I saw other people saying the same thing about nzbget ?

**Comment by hugbug** [comment]
If you need more speed you have to investigate what limits it. It can be CPU (check CPU usage), drive speed (check IO usage), network speed to your Usenet provider (even if you have fast connection your route to Usenet servers can be limited or provider can limit you).

Some useful tips can be found https://nzbget.net/performance-tips and https://nzbget.net/performing-speed-tests.

**Comment by Friday13th87** [comment]
as this one is old, but still open.
questions
1. are u talking about megabyte per second or megabit per second?
2. u heard something about connection overhead? bringing us to question 3
3. what internet connection are u using?

overall u can say taht u will have a combined overhead of around 9-13% and with those numbers u are landing exactly at the numbers u are writing, so that should be your fullspeed connection (if i would assume u have a 1gbit connection - but u are not speaking with clear words with "faster then 1000mbs", so how should someone help u?)
