### ISSUE TITLE
Tray icon in dark mode on Windows 10

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#66]
When running Windows 10 'hidden' Dark theme (official, from Microsoft), NZBGet's icon cannot be seen.

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize]
"AppsUseLightTheme"=dword:00000000
```

**Comment by hugbug** [comment]
Need an icon which looks well on Windows 10 taskbar.

**Comment by PureKrome** [comment]
![image](https://cloud.githubusercontent.com/assets/899878/13545598/6ee454d0-e2e5-11e5-9621-cf73cfe979d3.png)

**Comment by hugbug** [comment]
What's the point of adding screenshots? The problem is known. If you could contribute proper icons (for both light and dark themes) that would be great.

**Comment by PureKrome** [comment]
> What's the point of adding screenshots?
- just trying to be nice
- just trying to add clarification to the issue
- helping identify the issue to _other_ people who might pop in ... can actually _SEE_ the problem and go "Oh! now that i can totally understand the problem (because there's a picture) i think I can fix this issue. this isn't so bad... " ...
- `a picture tells a 1000 words`

ProTip: not hard to be nice when some random person _tries_ to help :cry: I guess i'm not helping then.

**Comment by hugbug** [comment]
This issue is half an year old and no one written here. It doesn't look like anyone is interested in a better explanation.

I didn't thought about the screenshots that they were addressed to other users. I thought you were trying to explain me what the problem is about as if I didn't know that. This is mostly because the issue tracker is used to communicate with developers, not between users (forum is a better platform for that).

Sorry for misunderstanding and hurting your feelings. My bad.

**Comment by Safihre** [comment]
On a small side note: the favicon of http://nzbget.net/ is not working at all.
