### ISSUE TITLE
Download read buffer only 4KB?

### ISSUE THREAD

**Issue by animetosho** [nzbget/nzbget#664]
I'll preface this with saying that I haven't verified anything, so apologies if I'm completely wrong here.

Looking through the code, it appears that articles are read [4KB at a time](https://github.com/nzbget/nzbget/blob/3a5bc85962cfc11525478e9021a40faa8d37cd9e/daemon/nntp/ArticleDownloader.cpp#L338). 4KB seems to be an awfully small buffer, particularly considering download speeds of today.

I think it would make sense to use a larger buffer for reading articles with. Larger buffers reduce a lot of overhead, in particular, syscalls.  
Larger buffers do consume more memory (likely less of an issue with typical machines today) and make bandwidth throttling or speed gauges less precise, but I'd think that you don't really need 4KB granularity nowadays.

Considering that articles are typically 750KB, I'd personally use something like 1MB, which would ensure overhead is minimal. This would make managing speed seem a little awkward on slower connections, although you might be able to manage it a little (e.g. measure speed using a large enough window).  
However, even something more modest like 64KB should be a massive improvement over 4KB, I'd think. You could also make the size configurable (and make the default larger) if you don't mind the extra complexity.

**Comment by hugbug** [comment]
The buffer is even smaller than you think, it's just [1024 bytes](https://github.com/nzbget/nzbget/blob/3a5bc85962cfc11525478e9021a40faa8d37cd9e/daemon/connect/Connection.cpp#L27). For one [`m_connection->ReadBuffer`](https://github.com/nzbget/nzbget/blob/3a5bc85962cfc11525478e9021a40faa8d37cd9e/daemon/nntp/ArticleDownloader.cpp#L353) call it makes four calls to [`recv`](https://github.com/nzbget/nzbget/blob/3a5bc85962cfc11525478e9021a40faa8d37cd9e/daemon/connect/Connection.cpp#L404).

In the past I've made many tests with this buffer with sizes from 1KB to 1MB as I suspected it could be an issue. In tests there were no any significant difference in speed or CPU usage. Therefore I kept it 1KB because as you mentioned it improves throttling and responsiveness.

If anyone is interested in performing his own tests - you can change the constant value and recompile the program. Or I can provide binaries compiled with different buffer sizes for you. If we can prove the buffer size has any effect I'll gladly add an option to adjust it.

**Comment by animetosho** [comment]
Thanks for the quick response!

I must be reading something a little wrong - from what I can tell, `Connection::ReadBuffer` only ever does something once (at most) because it sets `m_bufAvail` to 0, which means that all subsequent calls always return 0, meaning that all the reading is actually done in `Connection::TryRecv`, which completely bypasses the `m_readBuf` that the 1024 byte limit applies to, and reads into the 4096 byte `lineBuf`.  
I couldn't find any reference to `Connection::ReadLine` in ArticleDownloader.cpp

I'm not sure, but I think `recv` isn't buffered, so it seems like it would be a full syscall.

I've done no testing whatsoever, and don't actually have a setup to do so - all this is just conjecture on my part, so if you've already tested it, I guess that's that.

What triggered me to look, was that I've been tweaking my SIMD yEnc decoder recently, and managed to squeeze out some nice gains in performance. When I noticed that NZBGet was using 4KB buffers, I did some tests, and found that decoding speed when fed 4KB chunks is around 3x slower than when fed 64KB chunks. I don't expect yEnc decoding to be much of a CPU bottleneck, but as I noticed it, I thought I'd point it out.

Thanks again for the info.

**Comment by hugbug** [comment]
> the reading is actually done in Connection::TryRecv, which completely bypasses the m_readBuf that the 1024 byte limit applies to, and reads into the 4096 byte lineBuf.

You are totally right. I've pointed to a wrong function not used in downloading loop, sorry.

When I was integrating your SIMD-decoder, I tried different buffer sizes and ended up with 4KB. There were no much performance gain of using larger buffer at that time. 

I wonder where the 3x performance gain comes from. Do you have improvements in the decoder or is this merely an effect of CPU cache? Maybe you have a higher-end CPU with better cache which shows more effect?

Performance improvements are always welcome, especially if they are as easy to get as increasing an internal buffer. I should make more tests to ensure I haven't missed something.

Currently nzbget uses your decoder version from 2017. Was the decoder improved since that time? Maybe I should integrate the newest version into nzbget too.

Thank you.

**Comment by animetosho** [comment]
Ah okay, thanks for the clarification.

My gut feeling is that 4KB does seem small. I think the default Linux TCP receive window [is 87380 bytes](https://wiki.mikejung.biz/Sysctl_tweaks#net.ipv4.tcp_rmem) - unless you've specifically requested something different. For Windows, it seems to have been [64KB for older versions](https://docs.microsoft.com/en-us/windows-server/networking/technologies/network-subsystem/net-sub-performance-tuning-nics#bkmk_tcp_params) (is now auto-tuned, and documentation doesn't specify what the default is).  
Because of this, the benefits you get from increased granularity may be somewhat limited on faster connections, because the kernel may buffer more than the application. I'm not sure exactly how TCP window scaling works, but I imagine that 4KB is still useful for slower connections, although, the default TCP parameters are designed for all sorts of use cases, whilst Usenet downloading is mostly about bulk transfer.

The tests I ran were on the newer version of the yEnc decoder, where the difference should be more distinct. The decoder is mostly optimized for bulk processing, and not really the state handling outside of that, so it should perform better when given larger buffers.  
The scripts I use are in Javascript, which gave the 3x figures, however they did include Javascript overhead. Because of this, I re-ran them, breaking the data in chunks in C++ instead, and the difference is nowhere near as stark, so forget the over-exaggerated 3x claim as that's a mistake on my part (had never thought the Javascript<>C++ overhead to be that significant).

For reference, here's a quick test of the full decoder on one core of a Intel Xeon E3 1231v3 CPU:  
(Old=2017 version used in NZBGet, New=current development version (not released))

	Old (750KB article): 2113.60 MiB/s
	Old (4KB chunks):    2026.10 MiB/s
	Old (64KB chunks):   2085.84 MiB/s
	New (750KB article): 3891.73 MiB/s
	New (4KB chunks):    3438.75 MiB/s
	New (64KB chunks):   3897.33 MiB/s

Is [this](https://nzbget.net/performing-speed-tests) the procedure you use for your speed tests?  
If so, I might try some tests if I get around to it (no promises though). It does look like exact CPU/system impact may be harder to measure because it doesn't look like it's easy to isolate the download process for tools like `time`.

Again, this is all conjecture on my part from reading code with no testing - if you've already tested it, it's probably fine.

**Comment by animetosho** [comment]
Okay I ran some simple tests, using nzbget-21.1-testing-r2311 and adjusting only the lineBuf between 4KB and 1MB. Unsure how correct this is, as there's a fair amount of eyeballing and such, but here's what I got anyway.

I couldn't find the `SKIP_ARTICLE_WRITING` define [mentioned here](https://github.com/animetosho/node-yencode/issues/4#issuecomment-331736080), so all these tests actually write the data out. They're otherwise performed with the server on the same system as the client.

---

CPU: Core i7 7820X  
OS: Windows 10 1809  
Disk: Samsung 960 PRO  
Compiler: MSVC 2017 (using 2015 toolkit), x64

Download size: 7.81GB  
With 4KB buffers, download speed was around 483MB/s across 3 trials, CPU time was around 12s user, 44s kernel.  
With 1MB buffers (NServ's article size was 500K, as recommended), download speed was around 755MB/s across 3 trials, CPU time was around 15s user, 27s kernel.

CPU usage of NZBGet was around 20-25%, and NServ was around 25%, so neither maxed out the CPU.

I didn't bother with enabling cache on NServ - it wasn't CPU bound anyway, but I was curious whether the fact that it had to read off disk affected anything. So I modified Nyuu's test server to spit out dummy articles without reading from disk and ran it again.

Download size: ~8GB  
With 4KB buffers: 782-785MB/s  
With 1MB buffers: 1053MB/s

So there's definitely benefit from using larger buffers on this system from my tests.

---

CPU: AMD FX 8320  
OS: Linux 4.19 amd64  
Disk: Ramdisk  
Compiler: GCC 8.3.0 amd64

Download size: ~3GB  
With 4KB buffers: 965MB/s, CPU: 6s user, 8s kernel  
With 1MB buffers: 966MB/s, CPU: 6s user, 6s kernel

This was done using my test server rather than NServ. As with above, CPU never maxed out; NZBGet used around 50% (my test server used like 25%).  
Download speeds are basically the same, but there does seem to be a small benefit with reduced system load, probably due to fewer syscalls.

I don't know whether the difference in conclusions from the two tests are due to Linux/Windows efficiency differences, or due to one being written to disk vs ramdisk. I'm also unsure why neither was able to max out the CPU - all tests ran with 10 connections (maybe that wasn't enough?).  
I'm a little surprised at the results - I would've expected more of a difference in the second test, but perhaps that reflects what you've been seeing in your tests.

**Comment by hugbug** [comment]
**Thanks for testing!**

Source code define `SKIP_ARTICLE_WRITING` was superseded by new option `SkipWrite` which can be activated in NZBGet settings.

Not using cache in NServ means it yEnc-encodes on the fly. The encoder is very basic and not efficient.

Since the CPU wasn't fully consumed it seems the bottleneck is somewhere else other than yEnc-decoding. This can be for example the connection management part of NZBGet. Or maybe the disk writing (even to RAM-disk) took to much time.

If during tests I see too much of CPU idle, i usually try more connections, just to check if that helps. You could try 20 or even 100 connections.

I'm still going to do some comparison testing on my (slow) ARM box.

**Comment by animetosho** [comment]
Ah, missed that option, thanks.

Enabling it, I sometimes get odd speed readings though - like it'll say ~9MB/s (both average and current speed) even though it's downloading much faster than that?

**Comment by hugbug** [comment]
So the speed meter goes grazy on too high speeds :)

Try this: after the download ends - open the item in history, then click on Label "Total ->" in statistics box. It shows download stats for that nzb including average speed calculated from download time and size.

---

I've made tests on the ARM box. Tested 4KB and 64KB. The speed is the same. The 4KB version is actually even faster a little bit.

**Comment by animetosho** [comment]
Had a quick look - noticed that you use `int` (32-bit signed) for many measurements, so if it exceeds 2GB/s (?), it probably gives wrong results.  
Unfortunately, the history doesn't help as the claimed Download size is incorrect. I haven't looked much into why that's the case.

Thanks for the test. Perhaps Linux isn't affected so much by small buffers as Windows is (not particularly surprising, to be honest). Are you able to test on Windows? I wonder whether the recent CPU security mitigations (spectre/meltdown) have much of an impact when running on Intel CPUs...
