### ISSUE TITLE
Any way to prevent too long filenames/folders? (Windows 260 character size limit)

### ISSUE THREAD

**Issue by wjhanna** [nzbget/nzbget#683]
Running 21.0 (2 May 2019 edition), Server 1909 VM in Hyper-V. Intermediate files are stored on virtual disk, then using Categories are transferred to remote Windows file server via UNC path.

Asking this here because I can't sign up for the forums (well get approved, anyway). Is there any post-processing or setting in NZBGet that can monitor and prevent invalidly long names? I've run into this problem infrequently, but when it does happen it becomes a hassle to try and resolve.

**Comment by hugbug** [comment]
Windows and NZBGet support file names longer than 260. What problems do they cause in your case?

**Comment by wjhanna** [comment]
As an example, I had downloaded a very long file inside a very long folder. I was unable to delete due to an error related to file size and I suspect there was also an issue importing and renaming it into Sonarr as well (though it didn't specifically say that, logs aren't always perfect).

I've done several tests and I cannot duplicate the issue, but I do have an example download I can provide for troubleshooting if possible.

**Comment by hugbug** [comment]
The support for very long file names is an extra feature implemented in NZBGet. Reducing the length of file names isn't easily possible because the long names very often are created during unpacking, which isn't controlled by nzbget but rather by unrar. Unrar itself does also support very long file names.

The thing is if the file was downloaded without errors in NZBGet then what can I do? If other programs cannot process files with long names these programs should be improved. I believe Windows Explorer doesn't support long names, which is a shame but other file managers do better.

It should also be possible to rename (shorten) file names with a post-processing script.

If the problem is caused by very long name of the nzb-file then the name can be changed using a scan-script as precaution. That should be easier to do than to rename already created files with long names.

Anyway if you can't reproduce the issue at the moment, then I suggest to wait for it to reoccur and we can try to find a solution then.

---

I've activated all pending forum accounts. Missed the forum notification for them. Sorry.

**Comment by wjhanna** [comment]
I understand and you are correct, from a technical standpoint NZBGet and its processes are working correctly and as intended. Unfortunately 99% of my environment is Windows-based, so this is a problem I'll just continue to run into, or at least do some further research on workarounds..

I do have two of the recent files I've downloaded that caused the issue and can reproduce outside of NZBGet (they didn't get stuck in the Intermediate folder, like last time which did happen 2x in a row, but naturally under controlled circumstances they perform as intended) and can supply their info, the errors generated, and the specific .nzb files (preferably in private via email). But based on the above response, I'm not sure if troubleshooting any further would be a good use of time. I'll look into maybe doing a post-process script to try and catch these types in the future.

You can close the issue, thank you for the quick response.

**Comment by hugbug** [comment]
I'd like to take a look into logs. Please send them and other related info to nzbget@gmail.com.

**Comment by hugbug** [comment]
According to nzbget log the files were downloaded, repaired and combined without issues. Then Sonarr indeed failed to read the files. Sonarr is written in .NET and it seems it can easy  add support for very long file names. All they have to do is to add a line to the manifest file. Then you need enable the very long file names using Windows policy editor.
Please see https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/ for details.

Maybe you could also edit the Sonarr manifest file yourself too, using an resource editor or something like this. Anyway it is worth to ask the Sonarr devs.

On nzbget side you can use a relatively simple scan-script to limit length of nzb title (which is used as directory name). It turned out someone has already written it - [Scan Script - Truncate NZB Name Length](https://forum.nzbget.net/viewtopic.php?f=8&t=2178). To test the script add an nzb-file to queue. Moving nzbs from history to queue (via command "Download again") doesn't count.

To understand how the script work see [documentation for scan-scripts](https://nzbget.net/scan-scripts).
