### ISSUE TITLE
nzbget skips second unpack if nothing tp repair

### ISSUE THREAD

**Issue by sjpotter** [nzbget/nzbget#684]
I'm trying to setup nzbget, and I probaly had some permission issues, so the first extract failed because it couldn't create the directory structure, so I went to fix it and then do post process again on the failed file

but that failed, now with this

```
Wed Mar 18 20:18:16 2020        INFO    Repair not needed for test/file
Wed Mar 18 20:18:16 2020        INFO    Second unpack attempt skipped for test due to par-check not repaired anything
```

this does not seem like desired behavior to me.  

If the files existed because the post processing failed for some reason, I should be able to fix it outside of nzbget and post process again, not for nzbget to try to be smarter than me.  

I can imagine another scenario that might be impacted by this: if the files are actually bad, but instead of par2 reparing them, I get the bad file from somewhere else and drop it in place. par check will say it didn't repair anything, but it should be able to extract now.

**Comment by hugbug** [comment]
It isn't trying to be smarter than you.

During post-processing (after download or when you hit "post-process again") it tries to unpack. If unpack fails, it repairs and then unpacks again (second attempt). If repairer reports that there is nothing do, then you get this message "Second unpack attempt skipped". It doesn't try to unpack again because it tried that just a moment ago and nothing was changed after the first attempt. 

Check the whole log for error messages. There should be something from unrar.

Please post your nzb log (of that nzb only, not the whole program log), preferably via pastebin.com.

**Comment by sjpotter** [comment]
I'll have to try and duplicate the setup again, I fixed the underlying issue (path permissions) and extracted manually and deleted from history.  though if you say, it should act the way you describe, i trust you.  will either have to wait till i have to manually repair something or i have time to "break" the installation

**Comment by sjpotter** [comment]
So I've been able to duplicate it, but you're right when I fix the underlying problem, it does extract correctly.  However, perhaps the real bug is that nzbget doesn't do a good job of surfacing the actual issue.  it be nice to be able to filter the per nzb log by "error"

**Comment by hugbug** [comment]
You. An type "error" in the search box of the log dialog.
