### ISSUE TITLE
Cookie will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute.

### ISSUE THREAD

**Issue by Nothing4You** [nzbget/nzbget#725]
In Firefox 83:
> Cookie `Auth-Type` will be soon rejected because it has the `SameSite` attribute set to `None` or an invalid value, without the `secure` attribute. To know more about the `SameSite` attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

> Cookie `Auth-Token` will be soon rejected because it has the `SameSite` attribute set to `None` or an invalid value, without the `secure` attribute. To know more about the `SameSite` attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by Ramblurr** [comment]
I cannot use nzbget anymore (Firefox 79), initial login works, but any subsequent requests are failing because of this issue I believe.

Shortly after logging in, requests fail and the error message is shown:

```

Communication error!
Invalid Status: 502

```

![nzbget401](https://user-images.githubusercontent.com/14830/115200465-8c39e180-a0f4-11eb-9468-c29f0ebdb0e0.png)


**Update**

After a little more investigation, this isn't strictly a firefox issue. Also in google-chromium 88 I see the same behavior (but no warning in the console).

**Comment by hugbug** [comment]
Is option FormAuth active? Please test with FormAuth=no.

**Comment by hugbug** [comment]
I've added support for this attribute. It will be available in the new release. 

@Ramblurr I think your issue isn't related to SameSite attribute. Without this attribute the browser should still be able to connect. The lack of the attribute causes only messages in the console. If you want to try the new version before it is released and you use nzbget installer from nzbget download page - please send me a note to nzbget@gmail.com with the info on which OS and CPU architecture you use nzbget and I'll send you new installer.

I'm closing this issue as resolved because the requested feature has been implemented.

@Ramblurr If the problem remains with updated nzbget version please create a new issue.

**Comment by Ramblurr** [comment]
@hugbug you are correct, this was a red herring. I had a different issue that was a PBKAC. Thanks for the support.
