### ISSUE TITLE
lost queue + history completely after e2fsck lost+found

### ISSUE THREAD

**Issue by asratgh** [nzbget/nzbget#740]
My ext4 partition was auto-mounted as read-only. "errors=remount-ro" option in my fstab.  Nzbget was generating error messages. I rebooted using rescue disk and executed e2fsck and answered "y" to all recovery questions stating something "lost+found" folder. After rebooting, all my history+queue was empty BUT files are still present in the "queue" and "nzb" folders. 

How can I get back the queue, it was having around 200 nzbs in the queue.

My suggestion is that nzbget should stop downloading immediately automatically if it cannot flush the queue state from ram to the disk ( read only disk ).

I am using nzbget from Ubuntu 20.04 ( apt install nzbget ).

**Comment by hugbug** [comment]
The queue is saved in a very safe fashion:
- first it's saved into a temporary file;
- then the old file is renamed to xxx.old;
- then the new (temporary) file is renamed to correct name;
- then the old file xxx.old is deleted.

I don't know how to make it even better. I think your issue is caused by something else.
