### ISSUE TITLE
Feature Request: Add ability to upgrade to development version via UI

### ISSUE THREAD

**Issue by ravensorb** [nzbget/nzbget#769]
It would be great if there was a way to upgrade to the latest development release via the web interface (just like the beta and release versions)

**Comment by hugbug** [comment]
This is not possible because there are no such thing as development releases. There are stable and testing releases, which you can download from releases section or update to from web interface.

Then there is current development code. To use the latest code the program must be compiled for a specific platform. This happens during building of a new stable or testing release. If you want to use the latest code you have to compile the program yourself from sources.

**Comment by ravensorb** [comment]
Ok, thanks for the detailed feedback
