### ISSUE TITLE
RC4 not considered secure

### ISSUE THREAD

**Issue by CRTified** [nzbget/nzbget#87]
Hi, I just started using nzbGet and while setting up I noticed this text in the WebUI:

> One of the fastest cipher is RC4, it also provides strong 128 bit encryption. To select it use the cipher string "RC4-MD5" (if NZBGet was configured to use OpenSSL) or "NONE:+VERS-TLS-ALL:+ARCFOUR-128:+RSA:+MD5:+COMP-ALL" (if NZBGet was configured to use GnuTLS).

As some attacks on RC4 has been found, its usage in TLS got prohibited from the IETF (https://tools.ietf.org/html/rfc7465) and recommending this cipher may not be the best idea.

While RC4 is in fact a fast cipher, it does not provide proper security.

My version is nzbget 16.0-testing-r1441M.

**Comment by hugbug** [comment]
Although it's relevant when performing financial transactions I don't think the problem has any importance for Usenet downloading. Authorities can get all data directly from providers instead of cracking the transport stream.

Encryption in a Usenet downloader is mainly for two purposes:
- hide login data from neighbor-hackers;
- prevent traffic shaping by ISP.

Nonetheless I can add a hint about IETF considering RC4 insecure to inform the most paranoid users (who shouldn't download from Usenet anyway).

**Comment by CRTified** [comment]
Yes, I agree with you that it depends a lot on the threat model that one has, but it bothers me that RC4 gets called "strong". In my opinion this may be dangerous for uninformed user that learn from a pretty solid piece of software, that RC4 is "strong" and may be trusting this cipher for online-banking or other things, too.
As this is merely a cosmetic change, I'd think this should be easy to change.

I would remove "it also provides strong 128 bit encryption" and add "Note that RC4 is considered insecure by the IETF, but may be sufficient for the usage of NZBGet."

Thanks for taking this note serious, and not just ignoring it.
